/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.BlutgruppeSt;
import jooq.tables.Diagnose;
import jooq.tables.DiagnosetypSt;
import jooq.tables.FachrichtungSt;
import jooq.tables.FachrichtungStation;
import jooq.tables.Fall;
import jooq.tables.FallTypSt;
import jooq.tables.GeschlechtSt;
import jooq.tables.Icd10CodeSt;
import jooq.tables.MedPersonal;
import jooq.tables.NarkoseSt;
import jooq.tables.OpSaalSt;
import jooq.tables.OpTypSt;
import jooq.tables.Operation;
import jooq.tables.OpsCodeSt;
import jooq.tables.Patient;
import jooq.tables.Prozedur;
import jooq.tables.Rolle;
import jooq.tables.RolleSt;
import jooq.tables.StationSt;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pmiw21g05V01 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01</code>
     */
    public static final Pmiw21g05V01 PMIW21G05_V01 = new Pmiw21g05V01();

    /**
     * The table <code>pmiw21g05_v01.blutgruppe_st</code>.
     */
    public final BlutgruppeSt BLUTGRUPPE_ST = BlutgruppeSt.BLUTGRUPPE_ST;

    /**
     * The table <code>pmiw21g05_v01.diagnose</code>.
     */
    public final Diagnose DIAGNOSE = Diagnose.DIAGNOSE;

    /**
     * The table <code>pmiw21g05_v01.diagnosetyp_st</code>.
     */
    public final DiagnosetypSt DIAGNOSETYP_ST = DiagnosetypSt.DIAGNOSETYP_ST;

    /**
     * The table <code>pmiw21g05_v01.fachrichtung_st</code>.
     */
    public final FachrichtungSt FACHRICHTUNG_ST = FachrichtungSt.FACHRICHTUNG_ST;

    /**
     * The table <code>pmiw21g05_v01.fachrichtung_station</code>.
     */
    public final FachrichtungStation FACHRICHTUNG_STATION = FachrichtungStation.FACHRICHTUNG_STATION;

    /**
     * The table <code>pmiw21g05_v01.fall</code>.
     */
    public final Fall FALL = Fall.FALL;

    /**
     * The table <code>pmiw21g05_v01.fall_typ_st</code>.
     */
    public final FallTypSt FALL_TYP_ST = FallTypSt.FALL_TYP_ST;

    /**
     * The table <code>pmiw21g05_v01.geschlecht_st</code>.
     */
    public final GeschlechtSt GESCHLECHT_ST = GeschlechtSt.GESCHLECHT_ST;

    /**
     * The table <code>pmiw21g05_v01.icd10_code_st</code>.
     */
    public final Icd10CodeSt ICD10_CODE_ST = Icd10CodeSt.ICD10_CODE_ST;

    /**
     * The table <code>pmiw21g05_v01.med_personal</code>.
     */
    public final MedPersonal MED_PERSONAL = MedPersonal.MED_PERSONAL;

    /**
     * The table <code>pmiw21g05_v01.narkose_st</code>.
     */
    public final NarkoseSt NARKOSE_ST = NarkoseSt.NARKOSE_ST;

    /**
     * The table <code>pmiw21g05_v01.op_saal_st</code>.
     */
    public final OpSaalSt OP_SAAL_ST = OpSaalSt.OP_SAAL_ST;

    /**
     * The table <code>pmiw21g05_v01.op_typ_st</code>.
     */
    public final OpTypSt OP_TYP_ST = OpTypSt.OP_TYP_ST;

    /**
     * The table <code>pmiw21g05_v01.operation</code>.
     */
    public final Operation OPERATION = Operation.OPERATION;

    /**
     * The table <code>pmiw21g05_v01.ops_code_st</code>.
     */
    public final OpsCodeSt OPS_CODE_ST = OpsCodeSt.OPS_CODE_ST;

    /**
     * The table <code>pmiw21g05_v01.patient</code>.
     */
    public final Patient PATIENT = Patient.PATIENT;

    /**
     * The table <code>pmiw21g05_v01.prozedur</code>.
     */
    public final Prozedur PROZEDUR = Prozedur.PROZEDUR;

    /**
     * The table <code>pmiw21g05_v01.rolle</code>.
     */
    public final Rolle ROLLE = Rolle.ROLLE;

    /**
     * The table <code>pmiw21g05_v01.rolle_st</code>.
     */
    public final RolleSt ROLLE_ST = RolleSt.ROLLE_ST;

    /**
     * The table <code>pmiw21g05_v01.station_st</code>.
     */
    public final StationSt STATION_ST = StationSt.STATION_ST;

    /**
     * No further instances allowed
     */
    private Pmiw21g05V01() {
        super("pmiw21g05_v01", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BlutgruppeSt.BLUTGRUPPE_ST,
            Diagnose.DIAGNOSE,
            DiagnosetypSt.DIAGNOSETYP_ST,
            FachrichtungSt.FACHRICHTUNG_ST,
            FachrichtungStation.FACHRICHTUNG_STATION,
            Fall.FALL,
            FallTypSt.FALL_TYP_ST,
            GeschlechtSt.GESCHLECHT_ST,
            Icd10CodeSt.ICD10_CODE_ST,
            MedPersonal.MED_PERSONAL,
            NarkoseSt.NARKOSE_ST,
            OpSaalSt.OP_SAAL_ST,
            OpTypSt.OP_TYP_ST,
            Operation.OPERATION,
            OpsCodeSt.OPS_CODE_ST,
            Patient.PATIENT,
            Prozedur.PROZEDUR,
            Rolle.ROLLE,
            RolleSt.ROLLE_ST,
            StationSt.STATION_ST
        );
    }
}
