/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.BlutgruppeSt;
import jooq.tables.Diagnose;
import jooq.tables.DiagnosetypSt;
import jooq.tables.FachrichtungSt;
import jooq.tables.FachrichtungStation;
import jooq.tables.Fall;
import jooq.tables.FallTypSt;
import jooq.tables.GeschlechtSt;
import jooq.tables.Icd10CodeSt;
import jooq.tables.MedPersonal;
import jooq.tables.NarkoseSt;
import jooq.tables.OpSaalSt;
import jooq.tables.OpTypSt;
import jooq.tables.Operation;
import jooq.tables.OpsCodeSt;
import jooq.tables.Patient;
import jooq.tables.Prozedur;
import jooq.tables.Rolle;
import jooq.tables.RolleSt;
import jooq.tables.StationSt;


/**
 * Convenience access to all tables in pmiw21g05_v01.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pmiw21g05_v01.blutgruppe_st</code>.
     */
    public static final BlutgruppeSt BLUTGRUPPE_ST = BlutgruppeSt.BLUTGRUPPE_ST;

    /**
     * The table <code>pmiw21g05_v01.diagnose</code>.
     */
    public static final Diagnose DIAGNOSE = Diagnose.DIAGNOSE;

    /**
     * The table <code>pmiw21g05_v01.diagnosetyp_st</code>.
     */
    public static final DiagnosetypSt DIAGNOSETYP_ST = DiagnosetypSt.DIAGNOSETYP_ST;

    /**
     * The table <code>pmiw21g05_v01.fachrichtung_st</code>.
     */
    public static final FachrichtungSt FACHRICHTUNG_ST = FachrichtungSt.FACHRICHTUNG_ST;

    /**
     * The table <code>pmiw21g05_v01.fachrichtung_station</code>.
     */
    public static final FachrichtungStation FACHRICHTUNG_STATION = FachrichtungStation.FACHRICHTUNG_STATION;

    /**
     * The table <code>pmiw21g05_v01.fall</code>.
     */
    public static final Fall FALL = Fall.FALL;

    /**
     * The table <code>pmiw21g05_v01.fall_typ_st</code>.
     */
    public static final FallTypSt FALL_TYP_ST = FallTypSt.FALL_TYP_ST;

    /**
     * The table <code>pmiw21g05_v01.geschlecht_st</code>.
     */
    public static final GeschlechtSt GESCHLECHT_ST = GeschlechtSt.GESCHLECHT_ST;

    /**
     * The table <code>pmiw21g05_v01.icd10_code_st</code>.
     */
    public static final Icd10CodeSt ICD10_CODE_ST = Icd10CodeSt.ICD10_CODE_ST;

    /**
     * The table <code>pmiw21g05_v01.med_personal</code>.
     */
    public static final MedPersonal MED_PERSONAL = MedPersonal.MED_PERSONAL;

    /**
     * The table <code>pmiw21g05_v01.narkose_st</code>.
     */
    public static final NarkoseSt NARKOSE_ST = NarkoseSt.NARKOSE_ST;

    /**
     * The table <code>pmiw21g05_v01.op_saal_st</code>.
     */
    public static final OpSaalSt OP_SAAL_ST = OpSaalSt.OP_SAAL_ST;

    /**
     * The table <code>pmiw21g05_v01.op_typ_st</code>.
     */
    public static final OpTypSt OP_TYP_ST = OpTypSt.OP_TYP_ST;

    /**
     * The table <code>pmiw21g05_v01.operation</code>.
     */
    public static final Operation OPERATION = Operation.OPERATION;

    /**
     * The table <code>pmiw21g05_v01.ops_code_st</code>.
     */
    public static final OpsCodeSt OPS_CODE_ST = OpsCodeSt.OPS_CODE_ST;

    /**
     * The table <code>pmiw21g05_v01.patient</code>.
     */
    public static final Patient PATIENT = Patient.PATIENT;

    /**
     * The table <code>pmiw21g05_v01.prozedur</code>.
     */
    public static final Prozedur PROZEDUR = Prozedur.PROZEDUR;

    /**
     * The table <code>pmiw21g05_v01.rolle</code>.
     */
    public static final Rolle ROLLE = Rolle.ROLLE;

    /**
     * The table <code>pmiw21g05_v01.rolle_st</code>.
     */
    public static final RolleSt ROLLE_ST = RolleSt.ROLLE_ST;

    /**
     * The table <code>pmiw21g05_v01.station_st</code>.
     */
    public static final StationSt STATION_ST = StationSt.STATION_ST;
}
