/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlutgruppeSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private String blutgruppe;

    public BlutgruppeSt() {}

    public BlutgruppeSt(BlutgruppeSt value) {
        this.blutgruppe = value.blutgruppe;
    }

    public BlutgruppeSt(
        String blutgruppe
    ) {
        this.blutgruppe = blutgruppe;
    }

    /**
     * Getter for <code>pmiw21g05_v01.blutgruppe_st.blutgruppe</code>.
     */
    public String getBlutgruppe() {
        return this.blutgruppe;
    }

    /**
     * Setter for <code>pmiw21g05_v01.blutgruppe_st.blutgruppe</code>.
     */
    public void setBlutgruppe(String blutgruppe) {
        this.blutgruppe = blutgruppe;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BlutgruppeSt (");

        sb.append(blutgruppe);

        sb.append(")");
        return sb.toString();
    }
}
