/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diagnose implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       diagnoseId;
    private String        klartextDiagnose;
    private LocalDateTime datum;
    private LocalDateTime erstellZeit;
    private LocalDateTime bearbeiterZeit;
    private Boolean       storniert;
    private Integer       opId;
    private Integer       diagnosetyp;
    private String        icd10Code;
    private String        ersteller;
    private String        bearbeiter;

    public Diagnose() {}

    public Diagnose(Diagnose value) {
        this.diagnoseId = value.diagnoseId;
        this.klartextDiagnose = value.klartextDiagnose;
        this.datum = value.datum;
        this.erstellZeit = value.erstellZeit;
        this.bearbeiterZeit = value.bearbeiterZeit;
        this.storniert = value.storniert;
        this.opId = value.opId;
        this.diagnosetyp = value.diagnosetyp;
        this.icd10Code = value.icd10Code;
        this.ersteller = value.ersteller;
        this.bearbeiter = value.bearbeiter;
    }

    public Diagnose(
        Integer       diagnoseId,
        String        klartextDiagnose,
        LocalDateTime datum,
        LocalDateTime erstellZeit,
        LocalDateTime bearbeiterZeit,
        Boolean       storniert,
        Integer       opId,
        Integer       diagnosetyp,
        String        icd10Code,
        String        ersteller,
        String        bearbeiter
    ) {
        this.diagnoseId = diagnoseId;
        this.klartextDiagnose = klartextDiagnose;
        this.datum = datum;
        this.erstellZeit = erstellZeit;
        this.bearbeiterZeit = bearbeiterZeit;
        this.storniert = storniert;
        this.opId = opId;
        this.diagnosetyp = diagnosetyp;
        this.icd10Code = icd10Code;
        this.ersteller = ersteller;
        this.bearbeiter = bearbeiter;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.diagnose_id</code>.
     */
    public Integer getDiagnoseId() {
        return this.diagnoseId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.diagnose_id</code>.
     */
    public void setDiagnoseId(Integer diagnoseId) {
        this.diagnoseId = diagnoseId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.klartext_diagnose</code>.
     */
    public String getKlartextDiagnose() {
        return this.klartextDiagnose;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.klartext_diagnose</code>.
     */
    public void setKlartextDiagnose(String klartextDiagnose) {
        this.klartextDiagnose = klartextDiagnose;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.datum</code>.
     */
    public LocalDateTime getDatum() {
        return this.datum;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.datum</code>.
     */
    public void setDatum(LocalDateTime datum) {
        this.datum = datum;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.erstell_zeit</code>.
     */
    public LocalDateTime getErstellZeit() {
        return this.erstellZeit;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.erstell_zeit</code>.
     */
    public void setErstellZeit(LocalDateTime erstellZeit) {
        this.erstellZeit = erstellZeit;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.bearbeiter_zeit</code>.
     */
    public LocalDateTime getBearbeiterZeit() {
        return this.bearbeiterZeit;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.bearbeiter_zeit</code>.
     */
    public void setBearbeiterZeit(LocalDateTime bearbeiterZeit) {
        this.bearbeiterZeit = bearbeiterZeit;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.storniert</code>.
     */
    public Boolean getStorniert() {
        return this.storniert;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.storniert</code>.
     */
    public void setStorniert(Boolean storniert) {
        this.storniert = storniert;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.op_id</code>.
     */
    public Integer getOpId() {
        return this.opId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.op_id</code>.
     */
    public void setOpId(Integer opId) {
        this.opId = opId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.diagnosetyp</code>.
     */
    public Integer getDiagnosetyp() {
        return this.diagnosetyp;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.diagnosetyp</code>.
     */
    public void setDiagnosetyp(Integer diagnosetyp) {
        this.diagnosetyp = diagnosetyp;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.icd10_code</code>.
     */
    public String getIcd10Code() {
        return this.icd10Code;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.icd10_code</code>.
     */
    public void setIcd10Code(String icd10Code) {
        this.icd10Code = icd10Code;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.ersteller</code>.
     */
    public String getErsteller() {
        return this.ersteller;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.ersteller</code>.
     */
    public void setErsteller(String ersteller) {
        this.ersteller = ersteller;
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.bearbeiter</code>.
     */
    public String getBearbeiter() {
        return this.bearbeiter;
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.bearbeiter</code>.
     */
    public void setBearbeiter(String bearbeiter) {
        this.bearbeiter = bearbeiter;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Diagnose (");

        sb.append(diagnoseId);
        sb.append(", ").append(klartextDiagnose);
        sb.append(", ").append(datum);
        sb.append(", ").append(erstellZeit);
        sb.append(", ").append(bearbeiterZeit);
        sb.append(", ").append(storniert);
        sb.append(", ").append(opId);
        sb.append(", ").append(diagnosetyp);
        sb.append(", ").append(icd10Code);
        sb.append(", ").append(ersteller);
        sb.append(", ").append(bearbeiter);

        sb.append(")");
        return sb.toString();
    }
}
