/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FachrichtungStation implements Serializable {

    private static final long serialVersionUID = 1L;

    private String fachrichtungSt;
    private String stationSt;

    public FachrichtungStation() {}

    public FachrichtungStation(FachrichtungStation value) {
        this.fachrichtungSt = value.fachrichtungSt;
        this.stationSt = value.stationSt;
    }

    public FachrichtungStation(
        String fachrichtungSt,
        String stationSt
    ) {
        this.fachrichtungSt = fachrichtungSt;
        this.stationSt = stationSt;
    }

    /**
     * Getter for
     * <code>pmiw21g05_v01.fachrichtung_station.fachrichtung_st</code>.
     */
    public String getFachrichtungSt() {
        return this.fachrichtungSt;
    }

    /**
     * Setter for
     * <code>pmiw21g05_v01.fachrichtung_station.fachrichtung_st</code>.
     */
    public void setFachrichtungSt(String fachrichtungSt) {
        this.fachrichtungSt = fachrichtungSt;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_station.station_st</code>.
     */
    public String getStationSt() {
        return this.stationSt;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_station.station_st</code>.
     */
    public void setStationSt(String stationSt) {
        this.stationSt = stationSt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FachrichtungStation (");

        sb.append(fachrichtungSt);
        sb.append(", ").append(stationSt);

        sb.append(")");
        return sb.toString();
    }
}
