/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FachrichtungSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private String abteilung;
    private String bezeichnung;
    private String bezeichnungLang;
    private String abteilungstyp;
    private String bezeichnungLang_2;

    public FachrichtungSt() {}

    public FachrichtungSt(FachrichtungSt value) {
        this.abteilung = value.abteilung;
        this.bezeichnung = value.bezeichnung;
        this.bezeichnungLang = value.bezeichnungLang;
        this.abteilungstyp = value.abteilungstyp;
        this.bezeichnungLang_2 = value.bezeichnungLang_2;
    }

    public FachrichtungSt(
        String abteilung,
        String bezeichnung,
        String bezeichnungLang,
        String abteilungstyp,
        String bezeichnungLang_2
    ) {
        this.abteilung = abteilung;
        this.bezeichnung = bezeichnung;
        this.bezeichnungLang = bezeichnungLang;
        this.abteilungstyp = abteilungstyp;
        this.bezeichnungLang_2 = bezeichnungLang_2;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.abteilung</code>.
     */
    public String getAbteilung() {
        return this.abteilung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.abteilung</code>.
     */
    public void setAbteilung(String abteilung) {
        this.abteilung = abteilung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung</code>.
     */
    public String getBezeichnung() {
        return this.bezeichnung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung</code>.
     */
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang</code>.
     */
    public String getBezeichnungLang() {
        return this.bezeichnungLang;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang</code>.
     */
    public void setBezeichnungLang(String bezeichnungLang) {
        this.bezeichnungLang = bezeichnungLang;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.abteilungstyp</code>.
     */
    public String getAbteilungstyp() {
        return this.abteilungstyp;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.abteilungstyp</code>.
     */
    public void setAbteilungstyp(String abteilungstyp) {
        this.abteilungstyp = abteilungstyp;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang_2</code>.
     */
    public String getBezeichnungLang_2() {
        return this.bezeichnungLang_2;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang_2</code>.
     */
    public void setBezeichnungLang_2(String bezeichnungLang_2) {
        this.bezeichnungLang_2 = bezeichnungLang_2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FachrichtungSt (");

        sb.append(abteilung);
        sb.append(", ").append(bezeichnung);
        sb.append(", ").append(bezeichnungLang);
        sb.append(", ").append(abteilungstyp);
        sb.append(", ").append(bezeichnungLang_2);

        sb.append(")");
        return sb.toString();
    }
}
