/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fall implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       fallId;
    private LocalDateTime aufnahmedatum;
    private LocalDateTime entlassungsdatum;
    private LocalDateTime erstellZeit;
    private LocalDateTime bearbeiterZeit;
    private Byte          storniert;
    private Integer       patId;
    private String        stationSt;
    private String        ersteller;
    private String        bearbeiter;
    private Integer       fallTyp;

    public Fall() {}

    public Fall(Fall value) {
        this.fallId = value.fallId;
        this.aufnahmedatum = value.aufnahmedatum;
        this.entlassungsdatum = value.entlassungsdatum;
        this.erstellZeit = value.erstellZeit;
        this.bearbeiterZeit = value.bearbeiterZeit;
        this.storniert = value.storniert;
        this.patId = value.patId;
        this.stationSt = value.stationSt;
        this.ersteller = value.ersteller;
        this.bearbeiter = value.bearbeiter;
        this.fallTyp = value.fallTyp;
    }

    public Fall(
        Integer       fallId,
        LocalDateTime aufnahmedatum,
        LocalDateTime entlassungsdatum,
        LocalDateTime erstellZeit,
        LocalDateTime bearbeiterZeit,
        Byte          storniert,
        Integer       patId,
        String        stationSt,
        String        ersteller,
        String        bearbeiter,
        Integer       fallTyp
    ) {
        this.fallId = fallId;
        this.aufnahmedatum = aufnahmedatum;
        this.entlassungsdatum = entlassungsdatum;
        this.erstellZeit = erstellZeit;
        this.bearbeiterZeit = bearbeiterZeit;
        this.storniert = storniert;
        this.patId = patId;
        this.stationSt = stationSt;
        this.ersteller = ersteller;
        this.bearbeiter = bearbeiter;
        this.fallTyp = fallTyp;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.fall_id</code>.
     */
    public Integer getFallId() {
        return this.fallId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.fall_id</code>.
     */
    public void setFallId(Integer fallId) {
        this.fallId = fallId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.aufnahmedatum</code>.
     */
    public LocalDateTime getAufnahmedatum() {
        return this.aufnahmedatum;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.aufnahmedatum</code>.
     */
    public void setAufnahmedatum(LocalDateTime aufnahmedatum) {
        this.aufnahmedatum = aufnahmedatum;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.entlassungsdatum</code>.
     */
    public LocalDateTime getEntlassungsdatum() {
        return this.entlassungsdatum;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.entlassungsdatum</code>.
     */
    public void setEntlassungsdatum(LocalDateTime entlassungsdatum) {
        this.entlassungsdatum = entlassungsdatum;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.erstell_zeit</code>.
     */
    public LocalDateTime getErstellZeit() {
        return this.erstellZeit;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.erstell_zeit</code>.
     */
    public void setErstellZeit(LocalDateTime erstellZeit) {
        this.erstellZeit = erstellZeit;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.bearbeiter_zeit</code>.
     */
    public LocalDateTime getBearbeiterZeit() {
        return this.bearbeiterZeit;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.bearbeiter_zeit</code>.
     */
    public void setBearbeiterZeit(LocalDateTime bearbeiterZeit) {
        this.bearbeiterZeit = bearbeiterZeit;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.storniert</code>.
     */
    public Byte getStorniert() {
        return this.storniert;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.storniert</code>.
     */
    public void setStorniert(Byte storniert) {
        this.storniert = storniert;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.pat_id</code>.
     */
    public Integer getPatId() {
        return this.patId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.pat_id</code>.
     */
    public void setPatId(Integer patId) {
        this.patId = patId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.station_st</code>.
     */
    public String getStationSt() {
        return this.stationSt;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.station_st</code>.
     */
    public void setStationSt(String stationSt) {
        this.stationSt = stationSt;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.ersteller</code>.
     */
    public String getErsteller() {
        return this.ersteller;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.ersteller</code>.
     */
    public void setErsteller(String ersteller) {
        this.ersteller = ersteller;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.bearbeiter</code>.
     */
    public String getBearbeiter() {
        return this.bearbeiter;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.bearbeiter</code>.
     */
    public void setBearbeiter(String bearbeiter) {
        this.bearbeiter = bearbeiter;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall.fall_typ</code>.
     */
    public Integer getFallTyp() {
        return this.fallTyp;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall.fall_typ</code>.
     */
    public void setFallTyp(Integer fallTyp) {
        this.fallTyp = fallTyp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Fall (");

        sb.append(fallId);
        sb.append(", ").append(aufnahmedatum);
        sb.append(", ").append(entlassungsdatum);
        sb.append(", ").append(erstellZeit);
        sb.append(", ").append(bearbeiterZeit);
        sb.append(", ").append(storniert);
        sb.append(", ").append(patId);
        sb.append(", ").append(stationSt);
        sb.append(", ").append(ersteller);
        sb.append(", ").append(bearbeiter);
        sb.append(", ").append(fallTyp);

        sb.append(")");
        return sb.toString();
    }
}
