/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FallTypSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer fallTypId;
    private String  beschreibung;

    public FallTypSt() {}

    public FallTypSt(FallTypSt value) {
        this.fallTypId = value.fallTypId;
        this.beschreibung = value.beschreibung;
    }

    public FallTypSt(
        Integer fallTypId,
        String  beschreibung
    ) {
        this.fallTypId = fallTypId;
        this.beschreibung = beschreibung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall_typ_st.fall_typ_id</code>.
     */
    public Integer getFallTypId() {
        return this.fallTypId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall_typ_st.fall_typ_id</code>.
     */
    public void setFallTypId(Integer fallTypId) {
        this.fallTypId = fallTypId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall_typ_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return this.beschreibung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall_typ_st.beschreibung</code>.
     */
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FallTypSt (");

        sb.append(fallTypId);
        sb.append(", ").append(beschreibung);

        sb.append(")");
        return sb.toString();
    }
}
