/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeschlechtSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private String geschlecht;

    public GeschlechtSt() {}

    public GeschlechtSt(GeschlechtSt value) {
        this.geschlecht = value.geschlecht;
    }

    public GeschlechtSt(
        String geschlecht
    ) {
        this.geschlecht = geschlecht;
    }

    /**
     * Getter for <code>pmiw21g05_v01.geschlecht_st.geschlecht</code>.
     */
    public String getGeschlecht() {
        return this.geschlecht;
    }

    /**
     * Setter for <code>pmiw21g05_v01.geschlecht_st.geschlecht</code>.
     */
    public void setGeschlecht(String geschlecht) {
        this.geschlecht = geschlecht;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GeschlechtSt (");

        sb.append(geschlecht);

        sb.append(")");
        return sb.toString();
    }
}
