/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Icd10CodeSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private String icd10Code;
    private String beschreibung;

    public Icd10CodeSt() {}

    public Icd10CodeSt(Icd10CodeSt value) {
        this.icd10Code = value.icd10Code;
        this.beschreibung = value.beschreibung;
    }

    public Icd10CodeSt(
        String icd10Code,
        String beschreibung
    ) {
        this.icd10Code = icd10Code;
        this.beschreibung = beschreibung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.icd10_code_st.icd10_code</code>.
     */
    public String getIcd10Code() {
        return this.icd10Code;
    }

    /**
     * Setter for <code>pmiw21g05_v01.icd10_code_st.icd10_code</code>.
     */
    public void setIcd10Code(String icd10Code) {
        this.icd10Code = icd10Code;
    }

    /**
     * Getter for <code>pmiw21g05_v01.icd10_code_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return this.beschreibung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.icd10_code_st.beschreibung</code>.
     */
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(); //"Icd10CodeSt ("

        sb.append(icd10Code);
        //sb.append(", ").append(beschreibung);

        //sb.append(")");
        return sb.toString();
    }
}
