/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedPersonal implements Serializable {

    private static final long serialVersionUID = 1L;

    private String persId;
    private String nachnameVorname;
    private String name;
    private String vorname;
    private String titel;
    private String anrede;
    private String strasse;
    private String strasse_2;
    private String land;
    private String plz;
    private String stadt;
    private String telefonnummer;
    private String fachrichtung;
    private String fachrichtungKurz;

    public MedPersonal() {}

    public MedPersonal(MedPersonal value) {
        this.persId = value.persId;
        this.nachnameVorname = value.nachnameVorname;
        this.name = value.name;
        this.vorname = value.vorname;
        this.titel = value.titel;
        this.anrede = value.anrede;
        this.strasse = value.strasse;
        this.strasse_2 = value.strasse_2;
        this.land = value.land;
        this.plz = value.plz;
        this.stadt = value.stadt;
        this.telefonnummer = value.telefonnummer;
        this.fachrichtung = value.fachrichtung;
        this.fachrichtungKurz = value.fachrichtungKurz;
    }

    public MedPersonal(
        String persId,
        String nachnameVorname,
        String name,
        String vorname,
        String titel,
        String anrede,
        String strasse,
        String strasse_2,
        String land,
        String plz,
        String stadt,
        String telefonnummer,
        String fachrichtung,
        String fachrichtungKurz
    ) {
        this.persId = persId;
        this.nachnameVorname = nachnameVorname;
        this.name = name;
        this.vorname = vorname;
        this.titel = titel;
        this.anrede = anrede;
        this.strasse = strasse;
        this.strasse_2 = strasse_2;
        this.land = land;
        this.plz = plz;
        this.stadt = stadt;
        this.telefonnummer = telefonnummer;
        this.fachrichtung = fachrichtung;
        this.fachrichtungKurz = fachrichtungKurz;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.pers_ID</code>.
     */
    public String getPersId() {
        return this.persId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.pers_ID</code>.
     */
    public void setPersId(String persId) {
        this.persId = persId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.nachname_vorname</code>.
     */
    public String getNachnameVorname() {
        return this.nachnameVorname;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.nachname_vorname</code>.
     */
    public void setNachnameVorname(String nachnameVorname) {
        this.nachnameVorname = nachnameVorname;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.vorname</code>.
     */
    public String getVorname() {
        return this.vorname;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.vorname</code>.
     */
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.titel</code>.
     */
    public String getTitel() {
        return this.titel;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.titel</code>.
     */
    public void setTitel(String titel) {
        this.titel = titel;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.anrede</code>.
     */
    public String getAnrede() {
        return this.anrede;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.anrede</code>.
     */
    public void setAnrede(String anrede) {
        this.anrede = anrede;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.strasse</code>.
     */
    public String getStrasse() {
        return this.strasse;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.strasse</code>.
     */
    public void setStrasse(String strasse) {
        this.strasse = strasse;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.strasse_2</code>.
     */
    public String getStrasse_2() {
        return this.strasse_2;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.strasse_2</code>.
     */
    public void setStrasse_2(String strasse_2) {
        this.strasse_2 = strasse_2;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.land</code>.
     */
    public String getLand() {
        return this.land;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.land</code>.
     */
    public void setLand(String land) {
        this.land = land;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.plz</code>.
     */
    public String getPlz() {
        return this.plz;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.plz</code>.
     */
    public void setPlz(String plz) {
        this.plz = plz;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.stadt</code>.
     */
    public String getStadt() {
        return this.stadt;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.stadt</code>.
     */
    public void setStadt(String stadt) {
        this.stadt = stadt;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.telefonnummer</code>.
     */
    public String getTelefonnummer() {
        return this.telefonnummer;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.telefonnummer</code>.
     */
    public void setTelefonnummer(String telefonnummer) {
        this.telefonnummer = telefonnummer;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.fachrichtung</code>.
     */
    public String getFachrichtung() {
        return this.fachrichtung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.fachrichtung</code>.
     */
    public void setFachrichtung(String fachrichtung) {
        this.fachrichtung = fachrichtung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.fachrichtung_kurz</code>.
     */
    public String getFachrichtungKurz() {
        return this.fachrichtungKurz;
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.fachrichtung_kurz</code>.
     */
    public void setFachrichtungKurz(String fachrichtungKurz) {
        this.fachrichtungKurz = fachrichtungKurz;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MedPersonal (");

        sb.append(persId);
        sb.append(", ").append(nachnameVorname);
        sb.append(", ").append(name);
        sb.append(", ").append(vorname);
        sb.append(", ").append(titel);
        sb.append(", ").append(anrede);
        sb.append(", ").append(strasse);
        sb.append(", ").append(strasse_2);
        sb.append(", ").append(land);
        sb.append(", ").append(plz);
        sb.append(", ").append(stadt);
        sb.append(", ").append(telefonnummer);
        sb.append(", ").append(fachrichtung);
        sb.append(", ").append(fachrichtungKurz);

        sb.append(")");
        return sb.toString();
    }
}
