/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NarkoseSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer narkose;
    private String  beschreibung;

    public NarkoseSt() {}

    public NarkoseSt(NarkoseSt value) {
        this.narkose = value.narkose;
        this.beschreibung = value.beschreibung;
    }

    public NarkoseSt(
        Integer narkose,
        String  beschreibung
    ) {
        this.narkose = narkose;
        this.beschreibung = beschreibung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.narkose_st.narkose</code>.
     */
    public Integer getNarkose() {
        return this.narkose;
    }

    /**
     * Setter for <code>pmiw21g05_v01.narkose_st.narkose</code>.
     */
    public void setNarkose(Integer narkose) {
        this.narkose = narkose;
    }

    /**
     * Getter for <code>pmiw21g05_v01.narkose_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return this.beschreibung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.narkose_st.beschreibung</code>.
     */
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NarkoseSt (");

        sb.append(narkose);
        sb.append(", ").append(beschreibung);

        sb.append(")");
        return sb.toString();
    }
}
