/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpSaalSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer code;
    private String  beschreibung;

    public OpSaalSt() {}

    public OpSaalSt(OpSaalSt value) {
        this.code = value.code;
        this.beschreibung = value.beschreibung;
    }

    public OpSaalSt(
        Integer code,
        String  beschreibung
    ) {
        this.code = code;
        this.beschreibung = beschreibung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.op_saal_st.code</code>.
     */
    public Integer getCode() {
        return this.code;
    }

    /**
     * Setter for <code>pmiw21g05_v01.op_saal_st.code</code>.
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * Getter for <code>pmiw21g05_v01.op_saal_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return this.beschreibung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.op_saal_st.beschreibung</code>.
     */
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpSaalSt (");

        sb.append(code);
        sb.append(", ").append(beschreibung);

        sb.append(")");
        return sb.toString();
    }
}
