/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpsCodeSt implements Serializable {

    private static final long serialVersionUID = 1L;

    private String opsCode;
    private String beschreibung;

    public OpsCodeSt() {}

    public OpsCodeSt(OpsCodeSt value) {
        this.opsCode = value.opsCode;
        this.beschreibung = value.beschreibung;
    }

    public OpsCodeSt(
        String opsCode,
        String beschreibung
    ) {
        this.opsCode = opsCode;
        this.beschreibung = beschreibung;
    }

    /**
     * Getter for <code>pmiw21g05_v01.ops_code_st.ops_code</code>.
     */
    public String getOpsCode() {
        return this.opsCode;
    }

    /**
     * Setter for <code>pmiw21g05_v01.ops_code_st.ops_code</code>.
     */
    public void setOpsCode(String opsCode) {
        this.opsCode = opsCode;
    }

    /**
     * Getter for <code>pmiw21g05_v01.ops_code_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return this.beschreibung;
    }

    /**
     * Setter for <code>pmiw21g05_v01.ops_code_st.beschreibung</code>.
     */
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpsCodeSt (");

        sb.append(opsCode);
        sb.append(", ").append(beschreibung);

        sb.append(")");
        return sb.toString();
    }
}
