/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rolle implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       opId;
    private String        bearbeiter;
    private Integer       rolleSt;
    private LocalDateTime bearbeiterZeit;
    private LocalDateTime erstellZeit;
    private String        ersteller;
    private String        medPersonalPersId;
    private Boolean       storniert;

    public Rolle() {}

    public Rolle(Rolle value) {
        this.opId = value.opId;
        this.bearbeiter = value.bearbeiter;
        this.rolleSt = value.rolleSt;
        this.bearbeiterZeit = value.bearbeiterZeit;
        this.erstellZeit = value.erstellZeit;
        this.ersteller = value.ersteller;
        this.medPersonalPersId = value.medPersonalPersId;
        this.storniert = value.storniert;
    }

    public Rolle(
        Integer       opId,
        String        bearbeiter,
        Integer       rolleSt,
        LocalDateTime bearbeiterZeit,
        LocalDateTime erstellZeit,
        String        ersteller,
        String        medPersonalPersId,
        Boolean       storniert
    ) {
        this.opId = opId;
        this.bearbeiter = bearbeiter;
        this.rolleSt = rolleSt;
        this.bearbeiterZeit = bearbeiterZeit;
        this.erstellZeit = erstellZeit;
        this.ersteller = ersteller;
        this.medPersonalPersId = medPersonalPersId;
        this.storniert = storniert;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.op_id</code>.
     */
    public Integer getOpId() {
        return this.opId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.op_id</code>.
     */
    public void setOpId(Integer opId) {
        this.opId = opId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.bearbeiter</code>.
     */
    public String getBearbeiter() {
        return this.bearbeiter;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.bearbeiter</code>.
     */
    public void setBearbeiter(String bearbeiter) {
        this.bearbeiter = bearbeiter;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.rolle_st</code>.
     */
    public Integer getRolleSt() {
        return this.rolleSt;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.rolle_st</code>.
     */
    public void setRolleSt(Integer rolleSt) {
        this.rolleSt = rolleSt;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.bearbeiter_zeit</code>.
     */
    public LocalDateTime getBearbeiterZeit() {
        return this.bearbeiterZeit;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.bearbeiter_zeit</code>.
     */
    public void setBearbeiterZeit(LocalDateTime bearbeiterZeit) {
        this.bearbeiterZeit = bearbeiterZeit;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.erstell_zeit</code>.
     */
    public LocalDateTime getErstellZeit() {
        return this.erstellZeit;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.erstell_zeit</code>.
     */
    public void setErstellZeit(LocalDateTime erstellZeit) {
        this.erstellZeit = erstellZeit;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.ersteller</code>.
     */
    public String getErsteller() {
        return this.ersteller;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.ersteller</code>.
     */
    public void setErsteller(String ersteller) {
        this.ersteller = ersteller;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.med_personal_pers_ID</code>.
     */
    public String getMedPersonalPersId() {
        return this.medPersonalPersId;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.med_personal_pers_ID</code>.
     */
    public void setMedPersonalPersId(String medPersonalPersId) {
        this.medPersonalPersId = medPersonalPersId;
    }

    /**
     * Getter for <code>pmiw21g05_v01.rolle.storniert</code>.
     */
    public Boolean getStorniert() {
        return this.storniert;
    }

    /**
     * Setter for <code>pmiw21g05_v01.rolle.storniert</code>.
     */
    public void setStorniert(Boolean storniert) {
        this.storniert = storniert;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rolle (");

        sb.append(opId);
        sb.append(", ").append(bearbeiter);
        sb.append(", ").append(rolleSt);
        sb.append(", ").append(bearbeiterZeit);
        sb.append(", ").append(erstellZeit);
        sb.append(", ").append(ersteller);
        sb.append(", ").append(medPersonalPersId);
        sb.append(", ").append(storniert);

        sb.append(")");
        return sb.toString();
    }
}
