/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.BlutgruppeStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlutgruppeSt extends TableImpl<BlutgruppeStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.blutgruppe_st</code>
     */
    public static final BlutgruppeSt BLUTGRUPPE_ST = new BlutgruppeSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BlutgruppeStRecord> getRecordType() {
        return BlutgruppeStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.blutgruppe_st.blutgruppe</code>.
     */
    public final TableField<BlutgruppeStRecord, String> BLUTGRUPPE = createField(DSL.name("blutgruppe"), SQLDataType.VARCHAR(3).nullable(false), this, "");

    private BlutgruppeSt(Name alias, Table<BlutgruppeStRecord> aliased) {
        this(alias, aliased, null);
    }

    private BlutgruppeSt(Name alias, Table<BlutgruppeStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.blutgruppe_st</code> table
     * reference
     */
    public BlutgruppeSt(String alias) {
        this(DSL.name(alias), BLUTGRUPPE_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.blutgruppe_st</code> table
     * reference
     */
    public BlutgruppeSt(Name alias) {
        this(alias, BLUTGRUPPE_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.blutgruppe_st</code> table reference
     */
    public BlutgruppeSt() {
        this(DSL.name("blutgruppe_st"), null);
    }

    public <O extends Record> BlutgruppeSt(Table<O> child, ForeignKey<O, BlutgruppeStRecord> key) {
        super(child, key, BLUTGRUPPE_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public UniqueKey<BlutgruppeStRecord> getPrimaryKey() {
        return Keys.KEY_BLUTGRUPPE_ST_PRIMARY;
    }

    @Override
    public BlutgruppeSt as(String alias) {
        return new BlutgruppeSt(DSL.name(alias), this);
    }

    @Override
    public BlutgruppeSt as(Name alias) {
        return new BlutgruppeSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BlutgruppeSt rename(String name) {
        return new BlutgruppeSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BlutgruppeSt rename(Name name) {
        return new BlutgruppeSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
