/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.DiagnosetypStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiagnosetypSt extends TableImpl<DiagnosetypStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.diagnosetyp_st</code>
     */
    public static final DiagnosetypSt DIAGNOSETYP_ST = new DiagnosetypSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiagnosetypStRecord> getRecordType() {
        return DiagnosetypStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.diagnosetyp_st.diagnosetyp</code>.
     */
    public final TableField<DiagnosetypStRecord, Integer> DIAGNOSETYP = createField(DSL.name("diagnosetyp"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>pmiw21g05_v01.diagnosetyp_st.beschreibung</code>.
     */
    public final TableField<DiagnosetypStRecord, String> BESCHREIBUNG = createField(DSL.name("beschreibung"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private DiagnosetypSt(Name alias, Table<DiagnosetypStRecord> aliased) {
        this(alias, aliased, null);
    }

    private DiagnosetypSt(Name alias, Table<DiagnosetypStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.diagnosetyp_st</code> table
     * reference
     */
    public DiagnosetypSt(String alias) {
        this(DSL.name(alias), DIAGNOSETYP_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.diagnosetyp_st</code> table
     * reference
     */
    public DiagnosetypSt(Name alias) {
        this(alias, DIAGNOSETYP_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.diagnosetyp_st</code> table reference
     */
    public DiagnosetypSt() {
        this(DSL.name("diagnosetyp_st"), null);
    }

    public <O extends Record> DiagnosetypSt(Table<O> child, ForeignKey<O, DiagnosetypStRecord> key) {
        super(child, key, DIAGNOSETYP_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public Identity<DiagnosetypStRecord, Integer> getIdentity() {
        return (Identity<DiagnosetypStRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DiagnosetypStRecord> getPrimaryKey() {
        return Keys.KEY_DIAGNOSETYP_ST_PRIMARY;
    }

    @Override
    public DiagnosetypSt as(String alias) {
        return new DiagnosetypSt(DSL.name(alias), this);
    }

    @Override
    public DiagnosetypSt as(Name alias) {
        return new DiagnosetypSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DiagnosetypSt rename(String name) {
        return new DiagnosetypSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DiagnosetypSt rename(Name name) {
        return new DiagnosetypSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
