/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.FachrichtungStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FachrichtungSt extends TableImpl<FachrichtungStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.fachrichtung_st</code>
     */
    public static final FachrichtungSt FACHRICHTUNG_ST = new FachrichtungSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FachrichtungStRecord> getRecordType() {
        return FachrichtungStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.fachrichtung_st.abteilung</code>.
     */
    public final TableField<FachrichtungStRecord, String> ABTEILUNG = createField(DSL.name("abteilung"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>pmiw21g05_v01.fachrichtung_st.bezeichnung</code>.
     */
    public final TableField<FachrichtungStRecord, String> BEZEICHNUNG = createField(DSL.name("bezeichnung"), SQLDataType.VARCHAR(45).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang</code>.
     */
    public final TableField<FachrichtungStRecord, String> BEZEICHNUNG_LANG = createField(DSL.name("bezeichnung_lang"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>pmiw21g05_v01.fachrichtung_st.abteilungstyp</code>.
     */
    public final TableField<FachrichtungStRecord, String> ABTEILUNGSTYP = createField(DSL.name("abteilungstyp"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang_2</code>.
     */
    public final TableField<FachrichtungStRecord, String> BEZEICHNUNG_LANG_2 = createField(DSL.name("bezeichnung_lang_2"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    private FachrichtungSt(Name alias, Table<FachrichtungStRecord> aliased) {
        this(alias, aliased, null);
    }

    private FachrichtungSt(Name alias, Table<FachrichtungStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.fachrichtung_st</code> table
     * reference
     */
    public FachrichtungSt(String alias) {
        this(DSL.name(alias), FACHRICHTUNG_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.fachrichtung_st</code> table
     * reference
     */
    public FachrichtungSt(Name alias) {
        this(alias, FACHRICHTUNG_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.fachrichtung_st</code> table reference
     */
    public FachrichtungSt() {
        this(DSL.name("fachrichtung_st"), null);
    }

    public <O extends Record> FachrichtungSt(Table<O> child, ForeignKey<O, FachrichtungStRecord> key) {
        super(child, key, FACHRICHTUNG_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public UniqueKey<FachrichtungStRecord> getPrimaryKey() {
        return Keys.KEY_FACHRICHTUNG_ST_PRIMARY;
    }

    @Override
    public FachrichtungSt as(String alias) {
        return new FachrichtungSt(DSL.name(alias), this);
    }

    @Override
    public FachrichtungSt as(Name alias) {
        return new FachrichtungSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FachrichtungSt rename(String name) {
        return new FachrichtungSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FachrichtungSt rename(Name name) {
        return new FachrichtungSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
