/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.FallTypStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FallTypSt extends TableImpl<FallTypStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.fall_typ_st</code>
     */
    public static final FallTypSt FALL_TYP_ST = new FallTypSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FallTypStRecord> getRecordType() {
        return FallTypStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.fall_typ_st.fall_typ_id</code>.
     */
    public final TableField<FallTypStRecord, Integer> FALL_TYP_ID = createField(DSL.name("fall_typ_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>pmiw21g05_v01.fall_typ_st.beschreibung</code>.
     */
    public final TableField<FallTypStRecord, String> BESCHREIBUNG = createField(DSL.name("beschreibung"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private FallTypSt(Name alias, Table<FallTypStRecord> aliased) {
        this(alias, aliased, null);
    }

    private FallTypSt(Name alias, Table<FallTypStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.fall_typ_st</code> table reference
     */
    public FallTypSt(String alias) {
        this(DSL.name(alias), FALL_TYP_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.fall_typ_st</code> table reference
     */
    public FallTypSt(Name alias) {
        this(alias, FALL_TYP_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.fall_typ_st</code> table reference
     */
    public FallTypSt() {
        this(DSL.name("fall_typ_st"), null);
    }

    public <O extends Record> FallTypSt(Table<O> child, ForeignKey<O, FallTypStRecord> key) {
        super(child, key, FALL_TYP_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public Identity<FallTypStRecord, Integer> getIdentity() {
        return (Identity<FallTypStRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FallTypStRecord> getPrimaryKey() {
        return Keys.KEY_FALL_TYP_ST_PRIMARY;
    }

    @Override
    public FallTypSt as(String alias) {
        return new FallTypSt(DSL.name(alias), this);
    }

    @Override
    public FallTypSt as(Name alias) {
        return new FallTypSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FallTypSt rename(String name) {
        return new FallTypSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FallTypSt rename(Name name) {
        return new FallTypSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
