/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.GeschlechtStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeschlechtSt extends TableImpl<GeschlechtStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.geschlecht_st</code>
     */
    public static final GeschlechtSt GESCHLECHT_ST = new GeschlechtSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeschlechtStRecord> getRecordType() {
        return GeschlechtStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.geschlecht_st.geschlecht</code>.
     */
    public final TableField<GeschlechtStRecord, String> GESCHLECHT = createField(DSL.name("geschlecht"), SQLDataType.CHAR(1).nullable(false), this, "");

    private GeschlechtSt(Name alias, Table<GeschlechtStRecord> aliased) {
        this(alias, aliased, null);
    }

    private GeschlechtSt(Name alias, Table<GeschlechtStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.geschlecht_st</code> table
     * reference
     */
    public GeschlechtSt(String alias) {
        this(DSL.name(alias), GESCHLECHT_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.geschlecht_st</code> table
     * reference
     */
    public GeschlechtSt(Name alias) {
        this(alias, GESCHLECHT_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.geschlecht_st</code> table reference
     */
    public GeschlechtSt() {
        this(DSL.name("geschlecht_st"), null);
    }

    public <O extends Record> GeschlechtSt(Table<O> child, ForeignKey<O, GeschlechtStRecord> key) {
        super(child, key, GESCHLECHT_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public UniqueKey<GeschlechtStRecord> getPrimaryKey() {
        return Keys.KEY_GESCHLECHT_ST_PRIMARY;
    }

    @Override
    public GeschlechtSt as(String alias) {
        return new GeschlechtSt(DSL.name(alias), this);
    }

    @Override
    public GeschlechtSt as(Name alias) {
        return new GeschlechtSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GeschlechtSt rename(String name) {
        return new GeschlechtSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GeschlechtSt rename(Name name) {
        return new GeschlechtSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
