/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.Icd10CodeStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Icd10CodeSt extends TableImpl<Icd10CodeStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.icd10_code_st</code>
     */
    public static final Icd10CodeSt ICD10_CODE_ST = new Icd10CodeSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Icd10CodeStRecord> getRecordType() {
        return Icd10CodeStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.icd10_code_st.icd10_code</code>.
     */
    public final TableField<Icd10CodeStRecord, String> ICD10_CODE = createField(DSL.name("icd10_code"), SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>pmiw21g05_v01.icd10_code_st.beschreibung</code>.
     */
    public final TableField<Icd10CodeStRecord, String> BESCHREIBUNG = createField(DSL.name("beschreibung"), SQLDataType.VARCHAR(500).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    private Icd10CodeSt(Name alias, Table<Icd10CodeStRecord> aliased) {
        this(alias, aliased, null);
    }

    private Icd10CodeSt(Name alias, Table<Icd10CodeStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.icd10_code_st</code> table
     * reference
     */
    public Icd10CodeSt(String alias) {
        this(DSL.name(alias), ICD10_CODE_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.icd10_code_st</code> table
     * reference
     */
    public Icd10CodeSt(Name alias) {
        this(alias, ICD10_CODE_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.icd10_code_st</code> table reference
     */
    public Icd10CodeSt() {
        this(DSL.name("icd10_code_st"), null);
    }

    public <O extends Record> Icd10CodeSt(Table<O> child, ForeignKey<O, Icd10CodeStRecord> key) {
        super(child, key, ICD10_CODE_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public UniqueKey<Icd10CodeStRecord> getPrimaryKey() {
        return Keys.KEY_ICD10_CODE_ST_PRIMARY;
    }

    @Override
    public Icd10CodeSt as(String alias) {
        return new Icd10CodeSt(DSL.name(alias), this);
    }

    @Override
    public Icd10CodeSt as(Name alias) {
        return new Icd10CodeSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Icd10CodeSt rename(String name) {
        return new Icd10CodeSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Icd10CodeSt rename(Name name) {
        return new Icd10CodeSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
