/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.OpsCodeStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpsCodeSt extends TableImpl<OpsCodeStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.ops_code_st</code>
     */
    public static final OpsCodeSt OPS_CODE_ST = new OpsCodeSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpsCodeStRecord> getRecordType() {
        return OpsCodeStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.ops_code_st.ops_code</code>.
     */
    public final TableField<OpsCodeStRecord, String> OPS_CODE = createField(DSL.name("ops_code"), SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>pmiw21g05_v01.ops_code_st.beschreibung</code>.
     */
    public final TableField<OpsCodeStRecord, String> BESCHREIBUNG = createField(DSL.name("beschreibung"), SQLDataType.VARCHAR(500).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    private OpsCodeSt(Name alias, Table<OpsCodeStRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpsCodeSt(Name alias, Table<OpsCodeStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.ops_code_st</code> table reference
     */
    public OpsCodeSt(String alias) {
        this(DSL.name(alias), OPS_CODE_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.ops_code_st</code> table reference
     */
    public OpsCodeSt(Name alias) {
        this(alias, OPS_CODE_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.ops_code_st</code> table reference
     */
    public OpsCodeSt() {
        this(DSL.name("ops_code_st"), null);
    }

    public <O extends Record> OpsCodeSt(Table<O> child, ForeignKey<O, OpsCodeStRecord> key) {
        super(child, key, OPS_CODE_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public UniqueKey<OpsCodeStRecord> getPrimaryKey() {
        return Keys.KEY_OPS_CODE_ST_PRIMARY;
    }

    @Override
    public OpsCodeSt as(String alias) {
        return new OpsCodeSt(DSL.name(alias), this);
    }

    @Override
    public OpsCodeSt as(Name alias) {
        return new OpsCodeSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OpsCodeSt rename(String name) {
        return new OpsCodeSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OpsCodeSt rename(Name name) {
        return new OpsCodeSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
