/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Pmiw21g05V01;
import jooq.tables.records.OpTypStRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpTypSt extends TableImpl<OpTypStRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pmiw21g05_v01.op_typ_st</code>
     */
    public static final OpTypSt OP_TYP_ST = new OpTypSt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpTypStRecord> getRecordType() {
        return OpTypStRecord.class;
    }

    /**
     * The column <code>pmiw21g05_v01.op_typ_st.op_typ</code>.
     */
    public final TableField<OpTypStRecord, Integer> OP_TYP = createField(DSL.name("op_typ"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>pmiw21g05_v01.op_typ_st.beschreibung</code>.
     */
    public final TableField<OpTypStRecord, String> BESCHREIBUNG = createField(DSL.name("beschreibung"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private OpTypSt(Name alias, Table<OpTypStRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpTypSt(Name alias, Table<OpTypStRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.op_typ_st</code> table reference
     */
    public OpTypSt(String alias) {
        this(DSL.name(alias), OP_TYP_ST);
    }

    /**
     * Create an aliased <code>pmiw21g05_v01.op_typ_st</code> table reference
     */
    public OpTypSt(Name alias) {
        this(alias, OP_TYP_ST);
    }

    /**
     * Create a <code>pmiw21g05_v01.op_typ_st</code> table reference
     */
    public OpTypSt() {
        this(DSL.name("op_typ_st"), null);
    }

    public <O extends Record> OpTypSt(Table<O> child, ForeignKey<O, OpTypStRecord> key) {
        super(child, key, OP_TYP_ST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Pmiw21g05V01.PMIW21G05_V01;
    }

    @Override
    public Identity<OpTypStRecord, Integer> getIdentity() {
        return (Identity<OpTypStRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OpTypStRecord> getPrimaryKey() {
        return Keys.KEY_OP_TYP_ST_PRIMARY;
    }

    @Override
    public OpTypSt as(String alias) {
        return new OpTypSt(DSL.name(alias), this);
    }

    @Override
    public OpTypSt as(Name alias) {
        return new OpTypSt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OpTypSt rename(String name) {
        return new OpTypSt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OpTypSt rename(Name name) {
        return new OpTypSt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
