/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDateTime;

import jooq.tables.Diagnose;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiagnoseRecord extends UpdatableRecordImpl<DiagnoseRecord> implements Record11<Integer, String, LocalDateTime, LocalDateTime, LocalDateTime, Byte, Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.diagnose_id</code>.
     */
    public void setDiagnoseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.diagnose_id</code>.
     */
    public Integer getDiagnoseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.klartext_diagnose</code>.
     */
    public void setKlartextDiagnose(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.klartext_diagnose</code>.
     */
    public String getKlartextDiagnose() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.datum</code>.
     */
    public void setDatum(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.datum</code>.
     */
    public LocalDateTime getDatum() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.erstell_zeit</code>.
     */
    public void setErstellZeit(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.erstell_zeit</code>.
     */
    public LocalDateTime getErstellZeit() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.bearbeiter_zeit</code>.
     */
    public void setBearbeiterZeit(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.bearbeiter_zeit</code>.
     */
    public LocalDateTime getBearbeiterZeit() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.storniert</code>.
     */
    public void setStorniert(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.storniert</code>.
     */
    public Byte getStorniert() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.op_id</code>.
     */
    public void setOpId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.op_id</code>.
     */
    public Integer getOpId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.diagnosetyp</code>.
     */
    public void setDiagnosetyp(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.diagnosetyp</code>.
     */
    public Integer getDiagnosetyp() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.icd10_code</code>.
     */
    public void setIcd10Code(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.icd10_code</code>.
     */
    public String getIcd10Code() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.ersteller</code>.
     */
    public void setErsteller(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.ersteller</code>.
     */
    public String getErsteller() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnose.bearbeiter</code>.
     */
    public void setBearbeiter(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnose.bearbeiter</code>.
     */
    public String getBearbeiter() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, LocalDateTime, LocalDateTime, LocalDateTime, Byte, Integer, Integer, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, LocalDateTime, LocalDateTime, LocalDateTime, Byte, Integer, Integer, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Diagnose.DIAGNOSE.DIAGNOSE_ID;
    }

    @Override
    public Field<String> field2() {
        return Diagnose.DIAGNOSE.KLARTEXT_DIAGNOSE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Diagnose.DIAGNOSE.DATUM;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Diagnose.DIAGNOSE.ERSTELL_ZEIT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Diagnose.DIAGNOSE.BEARBEITER_ZEIT;
    }

    @Override
    public Field<Byte> field6() {
        return Diagnose.DIAGNOSE.STORNIERT;
    }

    @Override
    public Field<Integer> field7() {
        return Diagnose.DIAGNOSE.OP_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Diagnose.DIAGNOSE.DIAGNOSETYP;
    }

    @Override
    public Field<String> field9() {
        return Diagnose.DIAGNOSE.ICD10_CODE;
    }

    @Override
    public Field<String> field10() {
        return Diagnose.DIAGNOSE.ERSTELLER;
    }

    @Override
    public Field<String> field11() {
        return Diagnose.DIAGNOSE.BEARBEITER;
    }

    @Override
    public Integer component1() {
        return getDiagnoseId();
    }

    @Override
    public String component2() {
        return getKlartextDiagnose();
    }

    @Override
    public LocalDateTime component3() {
        return getDatum();
    }

    @Override
    public LocalDateTime component4() {
        return getErstellZeit();
    }

    @Override
    public LocalDateTime component5() {
        return getBearbeiterZeit();
    }

    @Override
    public Byte component6() {
        return getStorniert();
    }

    @Override
    public Integer component7() {
        return getOpId();
    }

    @Override
    public Integer component8() {
        return getDiagnosetyp();
    }

    @Override
    public String component9() {
        return getIcd10Code();
    }

    @Override
    public String component10() {
        return getErsteller();
    }

    @Override
    public String component11() {
        return getBearbeiter();
    }

    @Override
    public Integer value1() {
        return getDiagnoseId();
    }

    @Override
    public String value2() {
        return getKlartextDiagnose();
    }

    @Override
    public LocalDateTime value3() {
        return getDatum();
    }

    @Override
    public LocalDateTime value4() {
        return getErstellZeit();
    }

    @Override
    public LocalDateTime value5() {
        return getBearbeiterZeit();
    }

    @Override
    public Byte value6() {
        return getStorniert();
    }

    @Override
    public Integer value7() {
        return getOpId();
    }

    @Override
    public Integer value8() {
        return getDiagnosetyp();
    }

    @Override
    public String value9() {
        return getIcd10Code();
    }

    @Override
    public String value10() {
        return getErsteller();
    }

    @Override
    public String value11() {
        return getBearbeiter();
    }

    @Override
    public DiagnoseRecord value1(Integer value) {
        setDiagnoseId(value);
        return this;
    }

    @Override
    public DiagnoseRecord value2(String value) {
        setKlartextDiagnose(value);
        return this;
    }

    @Override
    public DiagnoseRecord value3(LocalDateTime value) {
        setDatum(value);
        return this;
    }

    @Override
    public DiagnoseRecord value4(LocalDateTime value) {
        setErstellZeit(value);
        return this;
    }

    @Override
    public DiagnoseRecord value5(LocalDateTime value) {
        setBearbeiterZeit(value);
        return this;
    }

    @Override
    public DiagnoseRecord value6(Byte value) {
        setStorniert(value);
        return this;
    }

    @Override
    public DiagnoseRecord value7(Integer value) {
        setOpId(value);
        return this;
    }

    @Override
    public DiagnoseRecord value8(Integer value) {
        setDiagnosetyp(value);
        return this;
    }

    @Override
    public DiagnoseRecord value9(String value) {
        setIcd10Code(value);
        return this;
    }

    @Override
    public DiagnoseRecord value10(String value) {
        setErsteller(value);
        return this;
    }

    @Override
    public DiagnoseRecord value11(String value) {
        setBearbeiter(value);
        return this;
    }

    @Override
    public DiagnoseRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4, LocalDateTime value5, Byte value6, Integer value7, Integer value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiagnoseRecord
     */
    public DiagnoseRecord() {
        super(Diagnose.DIAGNOSE);
    }

    /**
     * Create a detached, initialised DiagnoseRecord
     */
    public DiagnoseRecord(Integer diagnoseId, String klartextDiagnose, LocalDateTime datum, LocalDateTime erstellZeit, LocalDateTime bearbeiterZeit, Byte storniert, Integer opId, Integer diagnosetyp, String icd10Code, String ersteller, String bearbeiter) {
        super(Diagnose.DIAGNOSE);

        setDiagnoseId(diagnoseId);
        setKlartextDiagnose(klartextDiagnose);
        setDatum(datum);
        setErstellZeit(erstellZeit);
        setBearbeiterZeit(bearbeiterZeit);
        setStorniert(storniert);
        setOpId(opId);
        setDiagnosetyp(diagnosetyp);
        setIcd10Code(icd10Code);
        setErsteller(ersteller);
        setBearbeiter(bearbeiter);
    }

    /**
     * Create a detached, initialised DiagnoseRecord
     */
    public DiagnoseRecord(jooq.tables.pojos.Diagnose value) {
        super(Diagnose.DIAGNOSE);

        if (value != null) {
            setDiagnoseId(value.getDiagnoseId());
            setKlartextDiagnose(value.getKlartextDiagnose());
            setDatum(value.getDatum());
            setErstellZeit(value.getErstellZeit());
            setBearbeiterZeit(value.getBearbeiterZeit());
            setStorniert(value.getStorniert());
            setOpId(value.getOpId());
            setDiagnosetyp(value.getDiagnosetyp());
            setIcd10Code(value.getIcd10Code());
            setErsteller(value.getErsteller());
            setBearbeiter(value.getBearbeiter());
        }
    }
}
