/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.DiagnosetypSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiagnosetypStRecord extends UpdatableRecordImpl<DiagnosetypStRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.diagnosetyp_st.diagnosetyp</code>.
     */
    public void setDiagnosetyp(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnosetyp_st.diagnosetyp</code>.
     */
    public Integer getDiagnosetyp() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.diagnosetyp_st.beschreibung</code>.
     */
    public void setBeschreibung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.diagnosetyp_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DiagnosetypSt.DIAGNOSETYP_ST.DIAGNOSETYP;
    }

    @Override
    public Field<String> field2() {
        return DiagnosetypSt.DIAGNOSETYP_ST.BESCHREIBUNG;
    }

    @Override
    public Integer component1() {
        return getDiagnosetyp();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public Integer value1() {
        return getDiagnosetyp();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public DiagnosetypStRecord value1(Integer value) {
        setDiagnosetyp(value);
        return this;
    }

    @Override
    public DiagnosetypStRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public DiagnosetypStRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiagnosetypStRecord
     */
    public DiagnosetypStRecord() {
        super(DiagnosetypSt.DIAGNOSETYP_ST);
    }

    /**
     * Create a detached, initialised DiagnosetypStRecord
     */
    public DiagnosetypStRecord(Integer diagnosetyp, String beschreibung) {
        super(DiagnosetypSt.DIAGNOSETYP_ST);

        setDiagnosetyp(diagnosetyp);
        setBeschreibung(beschreibung);
    }

    /**
     * Create a detached, initialised DiagnosetypStRecord
     */
    public DiagnosetypStRecord(jooq.tables.pojos.DiagnosetypSt value) {
        super(DiagnosetypSt.DIAGNOSETYP_ST);

        if (value != null) {
            setDiagnosetyp(value.getDiagnosetyp());
            setBeschreibung(value.getBeschreibung());
        }
    }
}
