/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.FachrichtungSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FachrichtungStRecord extends UpdatableRecordImpl<FachrichtungStRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.abteilung</code>.
     */
    public void setAbteilung(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.abteilung</code>.
     */
    public String getAbteilung() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung</code>.
     */
    public void setBezeichnung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung</code>.
     */
    public String getBezeichnung() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang</code>.
     */
    public void setBezeichnungLang(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang</code>.
     */
    public String getBezeichnungLang() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.abteilungstyp</code>.
     */
    public void setAbteilungstyp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.abteilungstyp</code>.
     */
    public String getAbteilungstyp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang_2</code>.
     */
    public void setBezeichnungLang_2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fachrichtung_st.bezeichnung_lang_2</code>.
     */
    public String getBezeichnungLang_2() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FachrichtungSt.FACHRICHTUNG_ST.ABTEILUNG;
    }

    @Override
    public Field<String> field2() {
        return FachrichtungSt.FACHRICHTUNG_ST.BEZEICHNUNG;
    }

    @Override
    public Field<String> field3() {
        return FachrichtungSt.FACHRICHTUNG_ST.BEZEICHNUNG_LANG;
    }

    @Override
    public Field<String> field4() {
        return FachrichtungSt.FACHRICHTUNG_ST.ABTEILUNGSTYP;
    }

    @Override
    public Field<String> field5() {
        return FachrichtungSt.FACHRICHTUNG_ST.BEZEICHNUNG_LANG_2;
    }

    @Override
    public String component1() {
        return getAbteilung();
    }

    @Override
    public String component2() {
        return getBezeichnung();
    }

    @Override
    public String component3() {
        return getBezeichnungLang();
    }

    @Override
    public String component4() {
        return getAbteilungstyp();
    }

    @Override
    public String component5() {
        return getBezeichnungLang_2();
    }

    @Override
    public String value1() {
        return getAbteilung();
    }

    @Override
    public String value2() {
        return getBezeichnung();
    }

    @Override
    public String value3() {
        return getBezeichnungLang();
    }

    @Override
    public String value4() {
        return getAbteilungstyp();
    }

    @Override
    public String value5() {
        return getBezeichnungLang_2();
    }

    @Override
    public FachrichtungStRecord value1(String value) {
        setAbteilung(value);
        return this;
    }

    @Override
    public FachrichtungStRecord value2(String value) {
        setBezeichnung(value);
        return this;
    }

    @Override
    public FachrichtungStRecord value3(String value) {
        setBezeichnungLang(value);
        return this;
    }

    @Override
    public FachrichtungStRecord value4(String value) {
        setAbteilungstyp(value);
        return this;
    }

    @Override
    public FachrichtungStRecord value5(String value) {
        setBezeichnungLang_2(value);
        return this;
    }

    @Override
    public FachrichtungStRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FachrichtungStRecord
     */
    public FachrichtungStRecord() {
        super(FachrichtungSt.FACHRICHTUNG_ST);
    }

    /**
     * Create a detached, initialised FachrichtungStRecord
     */
    public FachrichtungStRecord(String abteilung, String bezeichnung, String bezeichnungLang, String abteilungstyp, String bezeichnungLang_2) {
        super(FachrichtungSt.FACHRICHTUNG_ST);

        setAbteilung(abteilung);
        setBezeichnung(bezeichnung);
        setBezeichnungLang(bezeichnungLang);
        setAbteilungstyp(abteilungstyp);
        setBezeichnungLang_2(bezeichnungLang_2);
    }

    /**
     * Create a detached, initialised FachrichtungStRecord
     */
    public FachrichtungStRecord(jooq.tables.pojos.FachrichtungSt value) {
        super(FachrichtungSt.FACHRICHTUNG_ST);

        if (value != null) {
            setAbteilung(value.getAbteilung());
            setBezeichnung(value.getBezeichnung());
            setBezeichnungLang(value.getBezeichnungLang());
            setAbteilungstyp(value.getAbteilungstyp());
            setBezeichnungLang_2(value.getBezeichnungLang_2());
        }
    }
}
