/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.FallTypSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FallTypStRecord extends UpdatableRecordImpl<FallTypStRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.fall_typ_st.fall_typ_id</code>.
     */
    public void setFallTypId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall_typ_st.fall_typ_id</code>.
     */
    public Integer getFallTypId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.fall_typ_st.beschreibung</code>.
     */
    public void setBeschreibung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.fall_typ_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FallTypSt.FALL_TYP_ST.FALL_TYP_ID;
    }

    @Override
    public Field<String> field2() {
        return FallTypSt.FALL_TYP_ST.BESCHREIBUNG;
    }

    @Override
    public Integer component1() {
        return getFallTypId();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public Integer value1() {
        return getFallTypId();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public FallTypStRecord value1(Integer value) {
        setFallTypId(value);
        return this;
    }

    @Override
    public FallTypStRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public FallTypStRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FallTypStRecord
     */
    public FallTypStRecord() {
        super(FallTypSt.FALL_TYP_ST);
    }

    /**
     * Create a detached, initialised FallTypStRecord
     */
    public FallTypStRecord(Integer fallTypId, String beschreibung) {
        super(FallTypSt.FALL_TYP_ST);

        setFallTypId(fallTypId);
        setBeschreibung(beschreibung);
    }

    /**
     * Create a detached, initialised FallTypStRecord
     */
    public FallTypStRecord(jooq.tables.pojos.FallTypSt value) {
        super(FallTypSt.FALL_TYP_ST);

        if (value != null) {
            setFallTypId(value.getFallTypId());
            setBeschreibung(value.getBeschreibung());
        }
    }
}
