/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.GeschlechtSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeschlechtStRecord extends UpdatableRecordImpl<GeschlechtStRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.geschlecht_st.geschlecht</code>.
     */
    public void setGeschlecht(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.geschlecht_st.geschlecht</code>.
     */
    public String getGeschlecht() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return GeschlechtSt.GESCHLECHT_ST.GESCHLECHT;
    }

    @Override
    public String component1() {
        return getGeschlecht();
    }

    @Override
    public String value1() {
        return getGeschlecht();
    }

    @Override
    public GeschlechtStRecord value1(String value) {
        setGeschlecht(value);
        return this;
    }

    @Override
    public GeschlechtStRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GeschlechtStRecord
     */
    public GeschlechtStRecord() {
        super(GeschlechtSt.GESCHLECHT_ST);
    }

    /**
     * Create a detached, initialised GeschlechtStRecord
     */
    public GeschlechtStRecord(String geschlecht) {
        super(GeschlechtSt.GESCHLECHT_ST);

        setGeschlecht(geschlecht);
    }

    /**
     * Create a detached, initialised GeschlechtStRecord
     */
    public GeschlechtStRecord(jooq.tables.pojos.GeschlechtSt value) {
        super(GeschlechtSt.GESCHLECHT_ST);

        if (value != null) {
            setGeschlecht(value.getGeschlecht());
        }
    }
}
