/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Icd10CodeSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Icd10CodeStRecord extends UpdatableRecordImpl<Icd10CodeStRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.icd10_code_st.icd10_code</code>.
     */
    public void setIcd10Code(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.icd10_code_st.icd10_code</code>.
     */
    public String getIcd10Code() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.icd10_code_st.beschreibung</code>.
     */
    public void setBeschreibung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.icd10_code_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Icd10CodeSt.ICD10_CODE_ST.ICD10_CODE;
    }

    @Override
    public Field<String> field2() {
        return Icd10CodeSt.ICD10_CODE_ST.BESCHREIBUNG;
    }

    @Override
    public String component1() {
        return getIcd10Code();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public String value1() {
        return getIcd10Code();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public Icd10CodeStRecord value1(String value) {
        setIcd10Code(value);
        return this;
    }

    @Override
    public Icd10CodeStRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public Icd10CodeStRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Icd10CodeStRecord
     */
    public Icd10CodeStRecord() {
        super(Icd10CodeSt.ICD10_CODE_ST);
    }

    /**
     * Create a detached, initialised Icd10CodeStRecord
     */
    public Icd10CodeStRecord(String icd10Code, String beschreibung) {
        super(Icd10CodeSt.ICD10_CODE_ST);

        setIcd10Code(icd10Code);
        setBeschreibung(beschreibung);
    }

    /**
     * Create a detached, initialised Icd10CodeStRecord
     */
    public Icd10CodeStRecord(jooq.tables.pojos.Icd10CodeSt value) {
        super(Icd10CodeSt.ICD10_CODE_ST);

        if (value != null) {
            setIcd10Code(value.getIcd10Code());
            setBeschreibung(value.getBeschreibung());
        }
    }
}
