/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.MedPersonal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedPersonalRecord extends UpdatableRecordImpl<MedPersonalRecord> implements Record14<String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.pers_ID</code>.
     */
    public void setPersId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.pers_ID</code>.
     */
    public String getPersId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.nachname_vorname</code>.
     */
    public void setNachnameVorname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.nachname_vorname</code>.
     */
    public String getNachnameVorname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.vorname</code>.
     */
    public void setVorname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.vorname</code>.
     */
    public String getVorname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.titel</code>.
     */
    public void setTitel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.titel</code>.
     */
    public String getTitel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.anrede</code>.
     */
    public void setAnrede(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.anrede</code>.
     */
    public String getAnrede() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.strasse</code>.
     */
    public void setStrasse(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.strasse</code>.
     */
    public String getStrasse() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.strasse_2</code>.
     */
    public void setStrasse_2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.strasse_2</code>.
     */
    public String getStrasse_2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.land</code>.
     */
    public void setLand(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.land</code>.
     */
    public String getLand() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.plz</code>.
     */
    public void setPlz(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.plz</code>.
     */
    public String getPlz() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.stadt</code>.
     */
    public void setStadt(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.stadt</code>.
     */
    public String getStadt() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.telefonnummer</code>.
     */
    public void setTelefonnummer(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.telefonnummer</code>.
     */
    public String getTelefonnummer() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.fachrichtung</code>.
     */
    public void setFachrichtung(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.fachrichtung</code>.
     */
    public String getFachrichtung() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pmiw21g05_v01.med_personal.fachrichtung_kurz</code>.
     */
    public void setFachrichtungKurz(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.med_personal.fachrichtung_kurz</code>.
     */
    public String getFachrichtungKurz() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MedPersonal.MED_PERSONAL.PERS_ID;
    }

    @Override
    public Field<String> field2() {
        return MedPersonal.MED_PERSONAL.NACHNAME_VORNAME;
    }

    @Override
    public Field<String> field3() {
        return MedPersonal.MED_PERSONAL.NAME;
    }

    @Override
    public Field<String> field4() {
        return MedPersonal.MED_PERSONAL.VORNAME;
    }

    @Override
    public Field<String> field5() {
        return MedPersonal.MED_PERSONAL.TITEL;
    }

    @Override
    public Field<String> field6() {
        return MedPersonal.MED_PERSONAL.ANREDE;
    }

    @Override
    public Field<String> field7() {
        return MedPersonal.MED_PERSONAL.STRASSE;
    }

    @Override
    public Field<String> field8() {
        return MedPersonal.MED_PERSONAL.STRASSE_2;
    }

    @Override
    public Field<String> field9() {
        return MedPersonal.MED_PERSONAL.LAND;
    }

    @Override
    public Field<String> field10() {
        return MedPersonal.MED_PERSONAL.PLZ;
    }

    @Override
    public Field<String> field11() {
        return MedPersonal.MED_PERSONAL.STADT;
    }

    @Override
    public Field<String> field12() {
        return MedPersonal.MED_PERSONAL.TELEFONNUMMER;
    }

    @Override
    public Field<String> field13() {
        return MedPersonal.MED_PERSONAL.FACHRICHTUNG;
    }

    @Override
    public Field<String> field14() {
        return MedPersonal.MED_PERSONAL.FACHRICHTUNG_KURZ;
    }

    @Override
    public String component1() {
        return getPersId();
    }

    @Override
    public String component2() {
        return getNachnameVorname();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getVorname();
    }

    @Override
    public String component5() {
        return getTitel();
    }

    @Override
    public String component6() {
        return getAnrede();
    }

    @Override
    public String component7() {
        return getStrasse();
    }

    @Override
    public String component8() {
        return getStrasse_2();
    }

    @Override
    public String component9() {
        return getLand();
    }

    @Override
    public String component10() {
        return getPlz();
    }

    @Override
    public String component11() {
        return getStadt();
    }

    @Override
    public String component12() {
        return getTelefonnummer();
    }

    @Override
    public String component13() {
        return getFachrichtung();
    }

    @Override
    public String component14() {
        return getFachrichtungKurz();
    }

    @Override
    public String value1() {
        return getPersId();
    }

    @Override
    public String value2() {
        return getNachnameVorname();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getVorname();
    }

    @Override
    public String value5() {
        return getTitel();
    }

    @Override
    public String value6() {
        return getAnrede();
    }

    @Override
    public String value7() {
        return getStrasse();
    }

    @Override
    public String value8() {
        return getStrasse_2();
    }

    @Override
    public String value9() {
        return getLand();
    }

    @Override
    public String value10() {
        return getPlz();
    }

    @Override
    public String value11() {
        return getStadt();
    }

    @Override
    public String value12() {
        return getTelefonnummer();
    }

    @Override
    public String value13() {
        return getFachrichtung();
    }

    @Override
    public String value14() {
        return getFachrichtungKurz();
    }

    @Override
    public MedPersonalRecord value1(String value) {
        setPersId(value);
        return this;
    }

    @Override
    public MedPersonalRecord value2(String value) {
        setNachnameVorname(value);
        return this;
    }

    @Override
    public MedPersonalRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MedPersonalRecord value4(String value) {
        setVorname(value);
        return this;
    }

    @Override
    public MedPersonalRecord value5(String value) {
        setTitel(value);
        return this;
    }

    @Override
    public MedPersonalRecord value6(String value) {
        setAnrede(value);
        return this;
    }

    @Override
    public MedPersonalRecord value7(String value) {
        setStrasse(value);
        return this;
    }

    @Override
    public MedPersonalRecord value8(String value) {
        setStrasse_2(value);
        return this;
    }

    @Override
    public MedPersonalRecord value9(String value) {
        setLand(value);
        return this;
    }

    @Override
    public MedPersonalRecord value10(String value) {
        setPlz(value);
        return this;
    }

    @Override
    public MedPersonalRecord value11(String value) {
        setStadt(value);
        return this;
    }

    @Override
    public MedPersonalRecord value12(String value) {
        setTelefonnummer(value);
        return this;
    }

    @Override
    public MedPersonalRecord value13(String value) {
        setFachrichtung(value);
        return this;
    }

    @Override
    public MedPersonalRecord value14(String value) {
        setFachrichtungKurz(value);
        return this;
    }

    @Override
    public MedPersonalRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedPersonalRecord
     */
    public MedPersonalRecord() {
        super(MedPersonal.MED_PERSONAL);
    }

    /**
     * Create a detached, initialised MedPersonalRecord
     */
    public MedPersonalRecord(String persId, String nachnameVorname, String name, String vorname, String titel, String anrede, String strasse, String strasse_2, String land, String plz, String stadt, String telefonnummer, String fachrichtung, String fachrichtungKurz) {
        super(MedPersonal.MED_PERSONAL);

        setPersId(persId);
        setNachnameVorname(nachnameVorname);
        setName(name);
        setVorname(vorname);
        setTitel(titel);
        setAnrede(anrede);
        setStrasse(strasse);
        setStrasse_2(strasse_2);
        setLand(land);
        setPlz(plz);
        setStadt(stadt);
        setTelefonnummer(telefonnummer);
        setFachrichtung(fachrichtung);
        setFachrichtungKurz(fachrichtungKurz);
    }

    /**
     * Create a detached, initialised MedPersonalRecord
     */
    public MedPersonalRecord(jooq.tables.pojos.MedPersonal value) {
        super(MedPersonal.MED_PERSONAL);

        if (value != null) {
            setPersId(value.getPersId());
            setNachnameVorname(value.getNachnameVorname());
            setName(value.getName());
            setVorname(value.getVorname());
            setTitel(value.getTitel());
            setAnrede(value.getAnrede());
            setStrasse(value.getStrasse());
            setStrasse_2(value.getStrasse_2());
            setLand(value.getLand());
            setPlz(value.getPlz());
            setStadt(value.getStadt());
            setTelefonnummer(value.getTelefonnummer());
            setFachrichtung(value.getFachrichtung());
            setFachrichtungKurz(value.getFachrichtungKurz());
        }
    }
}
