/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.NarkoseSt;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NarkoseStRecord extends TableRecordImpl<NarkoseStRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.narkose_st.narkose</code>.
     */
    public void setNarkose(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.narkose_st.narkose</code>.
     */
    public Integer getNarkose() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.narkose_st.beschreibung</code>.
     */
    public void setBeschreibung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.narkose_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NarkoseSt.NARKOSE_ST.NARKOSE;
    }

    @Override
    public Field<String> field2() {
        return NarkoseSt.NARKOSE_ST.BESCHREIBUNG;
    }

    @Override
    public Integer component1() {
        return getNarkose();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public Integer value1() {
        return getNarkose();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public NarkoseStRecord value1(Integer value) {
        setNarkose(value);
        return this;
    }

    @Override
    public NarkoseStRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public NarkoseStRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NarkoseStRecord
     */
    public NarkoseStRecord() {
        super(NarkoseSt.NARKOSE_ST);
    }

    /**
     * Create a detached, initialised NarkoseStRecord
     */
    public NarkoseStRecord(Integer narkose, String beschreibung) {
        super(NarkoseSt.NARKOSE_ST);

        setNarkose(narkose);
        setBeschreibung(beschreibung);
    }

    /**
     * Create a detached, initialised NarkoseStRecord
     */
    public NarkoseStRecord(jooq.tables.pojos.NarkoseSt value) {
        super(NarkoseSt.NARKOSE_ST);

        if (value != null) {
            setNarkose(value.getNarkose());
            setBeschreibung(value.getBeschreibung());
        }
    }
}
