/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.OpSaalSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpSaalStRecord extends UpdatableRecordImpl<OpSaalStRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.op_saal_st.code</code>.
     */
    public void setCode(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.op_saal_st.code</code>.
     */
    public Integer getCode() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.op_saal_st.beschreibung</code>.
     */
    public void setBeschreibung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.op_saal_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OpSaalSt.OP_SAAL_ST.CODE;
    }

    @Override
    public Field<String> field2() {
        return OpSaalSt.OP_SAAL_ST.BESCHREIBUNG;
    }

    @Override
    public Integer component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public Integer value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public OpSaalStRecord value1(Integer value) {
        setCode(value);
        return this;
    }

    @Override
    public OpSaalStRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public OpSaalStRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpSaalStRecord
     */
    public OpSaalStRecord() {
        super(OpSaalSt.OP_SAAL_ST);
    }

    /**
     * Create a detached, initialised OpSaalStRecord
     */
    public OpSaalStRecord(Integer code, String beschreibung) {
        super(OpSaalSt.OP_SAAL_ST);

        setCode(code);
        setBeschreibung(beschreibung);
    }

    /**
     * Create a detached, initialised OpSaalStRecord
     */
    public OpSaalStRecord(jooq.tables.pojos.OpSaalSt value) {
        super(OpSaalSt.OP_SAAL_ST);

        if (value != null) {
            setCode(value.getCode());
            setBeschreibung(value.getBeschreibung());
        }
    }
}
