/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.OpTypSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpTypStRecord extends UpdatableRecordImpl<OpTypStRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.op_typ_st.op_typ</code>.
     */
    public void setOpTyp(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.op_typ_st.op_typ</code>.
     */
    public Integer getOpTyp() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.op_typ_st.beschreibung</code>.
     */
    public void setBeschreibung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.op_typ_st.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OpTypSt.OP_TYP_ST.OP_TYP;
    }

    @Override
    public Field<String> field2() {
        return OpTypSt.OP_TYP_ST.BESCHREIBUNG;
    }

    @Override
    public Integer component1() {
        return getOpTyp();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public Integer value1() {
        return getOpTyp();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public OpTypStRecord value1(Integer value) {
        setOpTyp(value);
        return this;
    }

    @Override
    public OpTypStRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public OpTypStRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpTypStRecord
     */
    public OpTypStRecord() {
        super(OpTypSt.OP_TYP_ST);
    }

    /**
     * Create a detached, initialised OpTypStRecord
     */
    public OpTypStRecord(Integer opTyp, String beschreibung) {
        super(OpTypSt.OP_TYP_ST);

        setOpTyp(opTyp);
        setBeschreibung(beschreibung);
    }

    /**
     * Create a detached, initialised OpTypStRecord
     */
    public OpTypStRecord(jooq.tables.pojos.OpTypSt value) {
        super(OpTypSt.OP_TYP_ST);

        if (value != null) {
            setOpTyp(value.getOpTyp());
            setBeschreibung(value.getBeschreibung());
        }
    }
}
