/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import jooq.tables.Patient;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record16<Integer, String, String, LocalDate, String, String, String, LocalDateTime, String, LocalDateTime, Boolean, String, String, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.patient.pat_id</code>.
     */
    public void setPatId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.pat_id</code>.
     */
    public Integer getPatId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.vorname</code>.
     */
    public void setVorname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.vorname</code>.
     */
    public String getVorname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.geburtsdatum</code>.
     */
    public void setGeburtsdatum(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.geburtsdatum</code>.
     */
    public LocalDate getGeburtsdatum() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.blutgruppe</code>.
     */
    public void setBlutgruppe(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.blutgruppe</code>.
     */
    public String getBlutgruppe() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.geschlecht</code>.
     */
    public void setGeschlecht(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.geschlecht</code>.
     */
    public String getGeschlecht() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.bearbeiter</code>.
     */
    public void setBearbeiter(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.bearbeiter</code>.
     */
    public String getBearbeiter() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.bearbeiter_zeit</code>.
     */
    public void setBearbeiterZeit(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.bearbeiter_zeit</code>.
     */
    public LocalDateTime getBearbeiterZeit() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.ersteller</code>.
     */
    public void setErsteller(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.ersteller</code>.
     */
    public String getErsteller() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.erstell_zeit</code>.
     */
    public void setErstellZeit(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.erstell_zeit</code>.
     */
    public LocalDateTime getErstellZeit() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.storniert</code>.
     */
    public void setStorniert(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.storniert</code>.
     */
    public Boolean getStorniert() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.geburtsort</code>.
     */
    public void setGeburtsort(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.geburtsort</code>.
     */
    public String getGeburtsort() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.strasse</code>.
     */
    public void setStrasse(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.strasse</code>.
     */
    public String getStrasse() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.postleitzahl</code>.
     */
    public void setPostleitzahl(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.postleitzahl</code>.
     */
    public String getPostleitzahl() {
        return (String) get(13);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.telefonnummer</code>.
     */
    public void setTelefonnummer(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.telefonnummer</code>.
     */
    public String getTelefonnummer() {
        return (String) get(14);
    }

    /**
     * Setter for <code>pmiw21g05_v01.patient.notfall</code>.
     */
    public void setNotfall(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.patient.notfall</code>.
     */
    public Boolean getNotfall() {
        return (Boolean) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, String, String, LocalDate, String, String, String, LocalDateTime, String, LocalDateTime, Boolean, String, String, String, String, Boolean> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, String, String, LocalDate, String, String, String, LocalDateTime, String, LocalDateTime, Boolean, String, String, String, String, Boolean> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Patient.PATIENT.PAT_ID;
    }

    @Override
    public Field<String> field2() {
        return Patient.PATIENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Patient.PATIENT.VORNAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return Patient.PATIENT.GEBURTSDATUM;
    }

    @Override
    public Field<String> field5() {
        return Patient.PATIENT.BLUTGRUPPE;
    }

    @Override
    public Field<String> field6() {
        return Patient.PATIENT.GESCHLECHT;
    }

    @Override
    public Field<String> field7() {
        return Patient.PATIENT.BEARBEITER;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Patient.PATIENT.BEARBEITER_ZEIT;
    }

    @Override
    public Field<String> field9() {
        return Patient.PATIENT.ERSTELLER;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Patient.PATIENT.ERSTELL_ZEIT;
    }

    @Override
    public Field<Boolean> field11() {
        return Patient.PATIENT.STORNIERT;
    }

    @Override
    public Field<String> field12() {
        return Patient.PATIENT.GEBURTSORT;
    }

    @Override
    public Field<String> field13() {
        return Patient.PATIENT.STRASSE;
    }

    @Override
    public Field<String> field14() {
        return Patient.PATIENT.POSTLEITZAHL;
    }

    @Override
    public Field<String> field15() {
        return Patient.PATIENT.TELEFONNUMMER;
    }

    @Override
    public Field<Boolean> field16() {
        return Patient.PATIENT.NOTFALL;
    }

    @Override
    public Integer component1() {
        return getPatId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getVorname();
    }

    @Override
    public LocalDate component4() {
        return getGeburtsdatum();
    }

    @Override
    public String component5() {
        return getBlutgruppe();
    }

    @Override
    public String component6() {
        return getGeschlecht();
    }

    @Override
    public String component7() {
        return getBearbeiter();
    }

    @Override
    public LocalDateTime component8() {
        return getBearbeiterZeit();
    }

    @Override
    public String component9() {
        return getErsteller();
    }

    @Override
    public LocalDateTime component10() {
        return getErstellZeit();
    }

    @Override
    public Boolean component11() {
        return getStorniert();
    }

    @Override
    public String component12() {
        return getGeburtsort();
    }

    @Override
    public String component13() {
        return getStrasse();
    }

    @Override
    public String component14() {
        return getPostleitzahl();
    }

    @Override
    public String component15() {
        return getTelefonnummer();
    }

    @Override
    public Boolean component16() {
        return getNotfall();
    }

    @Override
    public Integer value1() {
        return getPatId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getVorname();
    }

    @Override
    public LocalDate value4() {
        return getGeburtsdatum();
    }

    @Override
    public String value5() {
        return getBlutgruppe();
    }

    @Override
    public String value6() {
        return getGeschlecht();
    }

    @Override
    public String value7() {
        return getBearbeiter();
    }

    @Override
    public LocalDateTime value8() {
        return getBearbeiterZeit();
    }

    @Override
    public String value9() {
        return getErsteller();
    }

    @Override
    public LocalDateTime value10() {
        return getErstellZeit();
    }

    @Override
    public Boolean value11() {
        return getStorniert();
    }

    @Override
    public String value12() {
        return getGeburtsort();
    }

    @Override
    public String value13() {
        return getStrasse();
    }

    @Override
    public String value14() {
        return getPostleitzahl();
    }

    @Override
    public String value15() {
        return getTelefonnummer();
    }

    @Override
    public Boolean value16() {
        return getNotfall();
    }

    @Override
    public PatientRecord value1(Integer value) {
        setPatId(value);
        return this;
    }

    @Override
    public PatientRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PatientRecord value3(String value) {
        setVorname(value);
        return this;
    }

    @Override
    public PatientRecord value4(LocalDate value) {
        setGeburtsdatum(value);
        return this;
    }

    @Override
    public PatientRecord value5(String value) {
        setBlutgruppe(value);
        return this;
    }

    @Override
    public PatientRecord value6(String value) {
        setGeschlecht(value);
        return this;
    }

    @Override
    public PatientRecord value7(String value) {
        setBearbeiter(value);
        return this;
    }

    @Override
    public PatientRecord value8(LocalDateTime value) {
        setBearbeiterZeit(value);
        return this;
    }

    @Override
    public PatientRecord value9(String value) {
        setErsteller(value);
        return this;
    }

    @Override
    public PatientRecord value10(LocalDateTime value) {
        setErstellZeit(value);
        return this;
    }

    @Override
    public PatientRecord value11(Boolean value) {
        setStorniert(value);
        return this;
    }

    @Override
    public PatientRecord value12(String value) {
        setGeburtsort(value);
        return this;
    }

    @Override
    public PatientRecord value13(String value) {
        setStrasse(value);
        return this;
    }

    @Override
    public PatientRecord value14(String value) {
        setPostleitzahl(value);
        return this;
    }

    @Override
    public PatientRecord value15(String value) {
        setTelefonnummer(value);
        return this;
    }

    @Override
    public PatientRecord value16(Boolean value) {
        setNotfall(value);
        return this;
    }

    @Override
    public PatientRecord values(Integer value1, String value2, String value3, LocalDate value4, String value5, String value6, String value7, LocalDateTime value8, String value9, LocalDateTime value10, Boolean value11, String value12, String value13, String value14, String value15, Boolean value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(Integer patId, String name, String vorname, LocalDate geburtsdatum, String blutgruppe, String geschlecht, String bearbeiter, LocalDateTime bearbeiterZeit, String ersteller, LocalDateTime erstellZeit, Boolean storniert, String geburtsort, String strasse, String postleitzahl, String telefonnummer, Boolean notfall) {
        super(Patient.PATIENT);

        setPatId(patId);
        setName(name);
        setVorname(vorname);
        setGeburtsdatum(geburtsdatum);
        setBlutgruppe(blutgruppe);
        setGeschlecht(geschlecht);
        setBearbeiter(bearbeiter);
        setBearbeiterZeit(bearbeiterZeit);
        setErsteller(ersteller);
        setErstellZeit(erstellZeit);
        setStorniert(storniert);
        setGeburtsort(geburtsort);
        setStrasse(strasse);
        setPostleitzahl(postleitzahl);
        setTelefonnummer(telefonnummer);
        setNotfall(notfall);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(jooq.tables.pojos.Patient value) {
        super(Patient.PATIENT);

        if (value != null) {
            setPatId(value.getPatId());
            setName(value.getName());
            setVorname(value.getVorname());
            setGeburtsdatum(value.getGeburtsdatum());
            setBlutgruppe(value.getBlutgruppe());
            setGeschlecht(value.getGeschlecht());
            setBearbeiter(value.getBearbeiter());
            setBearbeiterZeit(value.getBearbeiterZeit());
            setErsteller(value.getErsteller());
            setErstellZeit(value.getErstellZeit());
            setStorniert(value.getStorniert());
            setGeburtsort(value.getGeburtsort());
            setStrasse(value.getStrasse());
            setPostleitzahl(value.getPostleitzahl());
            setTelefonnummer(value.getTelefonnummer());
            setNotfall(value.getNotfall());
        }
    }
}
