/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDateTime;

import jooq.tables.Prozedur;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProzedurRecord extends UpdatableRecordImpl<ProzedurRecord> implements Record9<Integer, String, Boolean, LocalDateTime, LocalDateTime, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.proz_id</code>.
     */
    public void setProzId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.proz_id</code>.
     */
    public Integer getProzId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.anmerkung</code>.
     */
    public void setAnmerkung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.anmerkung</code>.
     */
    public String getAnmerkung() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.storniert</code>.
     */
    public void setStorniert(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.storniert</code>.
     */
    public Boolean getStorniert() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.erstell_zeit</code>.
     */
    public void setErstellZeit(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.erstell_zeit</code>.
     */
    public LocalDateTime getErstellZeit() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.bearbeiter_zeit</code>.
     */
    public void setBearbeiterZeit(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.bearbeiter_zeit</code>.
     */
    public LocalDateTime getBearbeiterZeit() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.op_id</code>.
     */
    public void setOpId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.op_id</code>.
     */
    public Integer getOpId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.ops_code</code>.
     */
    public void setOpsCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.ops_code</code>.
     */
    public String getOpsCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.bearbeiter</code>.
     */
    public void setBearbeiter(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.bearbeiter</code>.
     */
    public String getBearbeiter() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pmiw21g05_v01.prozedur.ersteller</code>.
     */
    public void setErsteller(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.prozedur.ersteller</code>.
     */
    public String getErsteller() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Boolean, LocalDateTime, LocalDateTime, Integer, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, Boolean, LocalDateTime, LocalDateTime, Integer, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Prozedur.PROZEDUR.PROZ_ID;
    }

    @Override
    public Field<String> field2() {
        return Prozedur.PROZEDUR.ANMERKUNG;
    }

    @Override
    public Field<Boolean> field3() {
        return Prozedur.PROZEDUR.STORNIERT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Prozedur.PROZEDUR.ERSTELL_ZEIT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Prozedur.PROZEDUR.BEARBEITER_ZEIT;
    }

    @Override
    public Field<Integer> field6() {
        return Prozedur.PROZEDUR.OP_ID;
    }

    @Override
    public Field<String> field7() {
        return Prozedur.PROZEDUR.OPS_CODE;
    }

    @Override
    public Field<String> field8() {
        return Prozedur.PROZEDUR.BEARBEITER;
    }

    @Override
    public Field<String> field9() {
        return Prozedur.PROZEDUR.ERSTELLER;
    }

    @Override
    public Integer component1() {
        return getProzId();
    }

    @Override
    public String component2() {
        return getAnmerkung();
    }

    @Override
    public Boolean component3() {
        return getStorniert();
    }

    @Override
    public LocalDateTime component4() {
        return getErstellZeit();
    }

    @Override
    public LocalDateTime component5() {
        return getBearbeiterZeit();
    }

    @Override
    public Integer component6() {
        return getOpId();
    }

    @Override
    public String component7() {
        return getOpsCode();
    }

    @Override
    public String component8() {
        return getBearbeiter();
    }

    @Override
    public String component9() {
        return getErsteller();
    }

    @Override
    public Integer value1() {
        return getProzId();
    }

    @Override
    public String value2() {
        return getAnmerkung();
    }

    @Override
    public Boolean value3() {
        return getStorniert();
    }

    @Override
    public LocalDateTime value4() {
        return getErstellZeit();
    }

    @Override
    public LocalDateTime value5() {
        return getBearbeiterZeit();
    }

    @Override
    public Integer value6() {
        return getOpId();
    }

    @Override
    public String value7() {
        return getOpsCode();
    }

    @Override
    public String value8() {
        return getBearbeiter();
    }

    @Override
    public String value9() {
        return getErsteller();
    }

    @Override
    public ProzedurRecord value1(Integer value) {
        setProzId(value);
        return this;
    }

    @Override
    public ProzedurRecord value2(String value) {
        setAnmerkung(value);
        return this;
    }

    @Override
    public ProzedurRecord value3(Boolean value) {
        setStorniert(value);
        return this;
    }

    @Override
    public ProzedurRecord value4(LocalDateTime value) {
        setErstellZeit(value);
        return this;
    }

    @Override
    public ProzedurRecord value5(LocalDateTime value) {
        setBearbeiterZeit(value);
        return this;
    }

    @Override
    public ProzedurRecord value6(Integer value) {
        setOpId(value);
        return this;
    }

    @Override
    public ProzedurRecord value7(String value) {
        setOpsCode(value);
        return this;
    }

    @Override
    public ProzedurRecord value8(String value) {
        setBearbeiter(value);
        return this;
    }

    @Override
    public ProzedurRecord value9(String value) {
        setErsteller(value);
        return this;
    }

    @Override
    public ProzedurRecord values(Integer value1, String value2, Boolean value3, LocalDateTime value4, LocalDateTime value5, Integer value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProzedurRecord
     */
    public ProzedurRecord() {
        super(Prozedur.PROZEDUR);
    }

    /**
     * Create a detached, initialised ProzedurRecord
     */
    public ProzedurRecord(Integer prozId, String anmerkung, Boolean storniert, LocalDateTime erstellZeit, LocalDateTime bearbeiterZeit, Integer opId, String opsCode, String bearbeiter, String ersteller) {
        super(Prozedur.PROZEDUR);

        setProzId(prozId);
        setAnmerkung(anmerkung);
        setStorniert(storniert);
        setErstellZeit(erstellZeit);
        setBearbeiterZeit(bearbeiterZeit);
        setOpId(opId);
        setOpsCode(opsCode);
        setBearbeiter(bearbeiter);
        setErsteller(ersteller);
    }

    /**
     * Create a detached, initialised ProzedurRecord
     */
    public ProzedurRecord(jooq.tables.pojos.Prozedur value) {
        super(Prozedur.PROZEDUR);

        if (value != null) {
            setProzId(value.getProzId());
            setAnmerkung(value.getAnmerkung());
            setStorniert(value.getStorniert());
            setErstellZeit(value.getErstellZeit());
            setBearbeiterZeit(value.getBearbeiterZeit());
            setOpId(value.getOpId());
            setOpsCode(value.getOpsCode());
            setBearbeiter(value.getBearbeiter());
            setErsteller(value.getErsteller());
        }
    }
}
