/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.StationSt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StationStRecord extends UpdatableRecordImpl<StationStRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pmiw21g05_v01.station_st.station</code>.
     */
    public void setStation(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.station_st.station</code>.
     */
    public String getStation() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pmiw21g05_v01.station_st.bezeichnung</code>.
     */
    public void setBezeichnung(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.station_st.bezeichnung</code>.
     */
    public String getBezeichnung() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pmiw21g05_v01.station_st.bezeichnung_lang</code>.
     */
    public void setBezeichnungLang(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.station_st.bezeichnung_lang</code>.
     */
    public String getBezeichnungLang() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pmiw21g05_v01.station_st.stationstyp</code>.
     */
    public void setStationstyp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pmiw21g05_v01.station_st.stationstyp</code>.
     */
    public String getStationstyp() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return StationSt.STATION_ST.STATION;
    }

    @Override
    public Field<String> field2() {
        return StationSt.STATION_ST.BEZEICHNUNG;
    }

    @Override
    public Field<String> field3() {
        return StationSt.STATION_ST.BEZEICHNUNG_LANG;
    }

    @Override
    public Field<String> field4() {
        return StationSt.STATION_ST.STATIONSTYP;
    }

    @Override
    public String component1() {
        return getStation();
    }

    @Override
    public String component2() {
        return getBezeichnung();
    }

    @Override
    public String component3() {
        return getBezeichnungLang();
    }

    @Override
    public String component4() {
        return getStationstyp();
    }

    @Override
    public String value1() {
        return getStation();
    }

    @Override
    public String value2() {
        return getBezeichnung();
    }

    @Override
    public String value3() {
        return getBezeichnungLang();
    }

    @Override
    public String value4() {
        return getStationstyp();
    }

    @Override
    public StationStRecord value1(String value) {
        setStation(value);
        return this;
    }

    @Override
    public StationStRecord value2(String value) {
        setBezeichnung(value);
        return this;
    }

    @Override
    public StationStRecord value3(String value) {
        setBezeichnungLang(value);
        return this;
    }

    @Override
    public StationStRecord value4(String value) {
        setStationstyp(value);
        return this;
    }

    @Override
    public StationStRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StationStRecord
     */
    public StationStRecord() {
        super(StationSt.STATION_ST);
    }

    /**
     * Create a detached, initialised StationStRecord
     */
    public StationStRecord(String station, String bezeichnung, String bezeichnungLang, String stationstyp) {
        super(StationSt.STATION_ST);

        setStation(station);
        setBezeichnung(bezeichnung);
        setBezeichnungLang(bezeichnungLang);
        setStationstyp(stationstyp);
    }

    /**
     * Create a detached, initialised StationStRecord
     */
    public StationStRecord(jooq.tables.pojos.StationSt value) {
        super(StationSt.STATION_ST);

        if (value != null) {
            setStation(value.getStation());
            setBezeichnung(value.getBezeichnung());
            setBezeichnungLang(value.getBezeichnungLang());
            setStationstyp(value.getStationstyp());
        }
    }
}
