/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.BlutgruppeSt;
import jooq.tables.records.BlutgruppeStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlutgruppeStDao extends DAOImpl<BlutgruppeStRecord, jooq.tables.pojos.BlutgruppeSt, String> {

    /**
     * Create a new BlutgruppeStDao without any configuration
     */
    public BlutgruppeStDao() {
        super(BlutgruppeSt.BLUTGRUPPE_ST, jooq.tables.pojos.BlutgruppeSt.class);
    }

    /**
     * Create a new BlutgruppeStDao with an attached configuration
     */
    public BlutgruppeStDao(Configuration configuration) {
        super(BlutgruppeSt.BLUTGRUPPE_ST, jooq.tables.pojos.BlutgruppeSt.class, configuration);
    }

    @Override
    public String getId(jooq.tables.pojos.BlutgruppeSt object) {
        return object.getBlutgruppe();
    }

    /**
     * Fetch records that have <code>blutgruppe BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.BlutgruppeSt> fetchRangeOfBlutgruppe(String lowerInclusive, String upperInclusive) {
        return fetchRange(BlutgruppeSt.BLUTGRUPPE_ST.BLUTGRUPPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>blutgruppe IN (values)</code>
     */
    public List<jooq.tables.pojos.BlutgruppeSt> fetchByBlutgruppe(String... values) {
        return fetch(BlutgruppeSt.BLUTGRUPPE_ST.BLUTGRUPPE, values);
    }

    /**
     * Fetch a unique record that has <code>blutgruppe = value</code>
     */
    public jooq.tables.pojos.BlutgruppeSt fetchOneByBlutgruppe(String value) {
        return fetchOne(BlutgruppeSt.BLUTGRUPPE_ST.BLUTGRUPPE, value);
    }
}
