/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import jooq.tables.Diagnose;
import jooq.tables.records.DiagnoseRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiagnoseDao extends DAOImpl<DiagnoseRecord, jooq.tables.pojos.Diagnose, Integer> {

    /**
     * Create a new DiagnoseDao without any configuration
     */
    public DiagnoseDao() {
        super(Diagnose.DIAGNOSE, jooq.tables.pojos.Diagnose.class);
    }

    /**
     * Create a new DiagnoseDao with an attached configuration
     */
    public DiagnoseDao(Configuration configuration) {
        super(Diagnose.DIAGNOSE, jooq.tables.pojos.Diagnose.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.Diagnose object) {
        return object.getDiagnoseId();
    }

    /**
     * Fetch records that have <code>diagnose_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfDiagnoseId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.DIAGNOSE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>diagnose_id IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByDiagnoseId(Integer... values) {
        return fetch(Diagnose.DIAGNOSE.DIAGNOSE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>diagnose_id = value</code>
     */
    public jooq.tables.pojos.Diagnose fetchOneByDiagnoseId(Integer value) {
        return fetchOne(Diagnose.DIAGNOSE.DIAGNOSE_ID, value);
    }

    /**
     * Fetch records that have <code>klartext_diagnose BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfKlartextDiagnose(String lowerInclusive, String upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.KLARTEXT_DIAGNOSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>klartext_diagnose IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByKlartextDiagnose(String... values) {
        return fetch(Diagnose.DIAGNOSE.KLARTEXT_DIAGNOSE, values);
    }

    /**
     * Fetch records that have <code>datum BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfDatum(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.DATUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datum IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByDatum(LocalDateTime... values) {
        return fetch(Diagnose.DIAGNOSE.DATUM, values);
    }

    /**
     * Fetch records that have <code>erstell_zeit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfErstellZeit(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.ERSTELL_ZEIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>erstell_zeit IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByErstellZeit(LocalDateTime... values) {
        return fetch(Diagnose.DIAGNOSE.ERSTELL_ZEIT, values);
    }

    /**
     * Fetch records that have <code>bearbeiter_zeit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfBearbeiterZeit(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.BEARBEITER_ZEIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bearbeiter_zeit IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByBearbeiterZeit(LocalDateTime... values) {
        return fetch(Diagnose.DIAGNOSE.BEARBEITER_ZEIT, values);
    }

    /**
     * Fetch records that have <code>storniert BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfStorniert(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.STORNIERT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>storniert IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByStorniert(Byte... values) {
        return fetch(Diagnose.DIAGNOSE.STORNIERT, values);
    }

    /**
     * Fetch records that have <code>op_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfOpId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.OP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>op_id IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByOpId(Integer... values) {
        return fetch(Diagnose.DIAGNOSE.OP_ID, values);
    }

    /**
     * Fetch records that have <code>diagnosetyp BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfDiagnosetyp(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.DIAGNOSETYP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>diagnosetyp IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByDiagnosetyp(Integer... values) {
        return fetch(Diagnose.DIAGNOSE.DIAGNOSETYP, values);
    }

    /**
     * Fetch records that have <code>icd10_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfIcd10Code(String lowerInclusive, String upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.ICD10_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>icd10_code IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByIcd10Code(String... values) {
        return fetch(Diagnose.DIAGNOSE.ICD10_CODE, values);
    }

    /**
     * Fetch records that have <code>ersteller BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfErsteller(String lowerInclusive, String upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.ERSTELLER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ersteller IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByErsteller(String... values) {
        return fetch(Diagnose.DIAGNOSE.ERSTELLER, values);
    }

    /**
     * Fetch records that have <code>bearbeiter BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchRangeOfBearbeiter(String lowerInclusive, String upperInclusive) {
        return fetchRange(Diagnose.DIAGNOSE.BEARBEITER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bearbeiter IN (values)</code>
     */
    public List<jooq.tables.pojos.Diagnose> fetchByBearbeiter(String... values) {
        return fetch(Diagnose.DIAGNOSE.BEARBEITER, values);
    }
}
