/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.FachrichtungStation;
import jooq.tables.records.FachrichtungStationRecord;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FachrichtungStationDao extends DAOImpl<FachrichtungStationRecord, jooq.tables.pojos.FachrichtungStation, Record2<String, String>> {

    /**
     * Create a new FachrichtungStationDao without any configuration
     */
    public FachrichtungStationDao() {
        super(FachrichtungStation.FACHRICHTUNG_STATION, jooq.tables.pojos.FachrichtungStation.class);
    }

    /**
     * Create a new FachrichtungStationDao with an attached configuration
     */
    public FachrichtungStationDao(Configuration configuration) {
        super(FachrichtungStation.FACHRICHTUNG_STATION, jooq.tables.pojos.FachrichtungStation.class, configuration);
    }

    @Override
    public Record2<String, String> getId(jooq.tables.pojos.FachrichtungStation object) {
        return compositeKeyRecord(object.getFachrichtungSt(), object.getStationSt());
    }

    /**
     * Fetch records that have <code>fachrichtung_st BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.FachrichtungStation> fetchRangeOfFachrichtungSt(String lowerInclusive, String upperInclusive) {
        return fetchRange(FachrichtungStation.FACHRICHTUNG_STATION.FACHRICHTUNG_ST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fachrichtung_st IN (values)</code>
     */
    public List<jooq.tables.pojos.FachrichtungStation> fetchByFachrichtungSt(String... values) {
        return fetch(FachrichtungStation.FACHRICHTUNG_STATION.FACHRICHTUNG_ST, values);
    }

    /**
     * Fetch records that have <code>station_st BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.FachrichtungStation> fetchRangeOfStationSt(String lowerInclusive, String upperInclusive) {
        return fetchRange(FachrichtungStation.FACHRICHTUNG_STATION.STATION_ST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>station_st IN (values)</code>
     */
    public List<jooq.tables.pojos.FachrichtungStation> fetchByStationSt(String... values) {
        return fetch(FachrichtungStation.FACHRICHTUNG_STATION.STATION_ST, values);
    }
}
