/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.FallTypSt;
import jooq.tables.records.FallTypStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FallTypStDao extends DAOImpl<FallTypStRecord, jooq.tables.pojos.FallTypSt, Integer> {

    /**
     * Create a new FallTypStDao without any configuration
     */
    public FallTypStDao() {
        super(FallTypSt.FALL_TYP_ST, jooq.tables.pojos.FallTypSt.class);
    }

    /**
     * Create a new FallTypStDao with an attached configuration
     */
    public FallTypStDao(Configuration configuration) {
        super(FallTypSt.FALL_TYP_ST, jooq.tables.pojos.FallTypSt.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.FallTypSt object) {
        return object.getFallTypId();
    }

    /**
     * Fetch records that have <code>fall_typ_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.FallTypSt> fetchRangeOfFallTypId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FallTypSt.FALL_TYP_ST.FALL_TYP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fall_typ_id IN (values)</code>
     */
    public List<jooq.tables.pojos.FallTypSt> fetchByFallTypId(Integer... values) {
        return fetch(FallTypSt.FALL_TYP_ST.FALL_TYP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>fall_typ_id = value</code>
     */
    public jooq.tables.pojos.FallTypSt fetchOneByFallTypId(Integer value) {
        return fetchOne(FallTypSt.FALL_TYP_ST.FALL_TYP_ID, value);
    }

    /**
     * Fetch records that have <code>beschreibung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.FallTypSt> fetchRangeOfBeschreibung(String lowerInclusive, String upperInclusive) {
        return fetchRange(FallTypSt.FALL_TYP_ST.BESCHREIBUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>beschreibung IN (values)</code>
     */
    public List<jooq.tables.pojos.FallTypSt> fetchByBeschreibung(String... values) {
        return fetch(FallTypSt.FALL_TYP_ST.BESCHREIBUNG, values);
    }
}
