/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.GeschlechtSt;
import jooq.tables.records.GeschlechtStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeschlechtStDao extends DAOImpl<GeschlechtStRecord, jooq.tables.pojos.GeschlechtSt, String> {

    /**
     * Create a new GeschlechtStDao without any configuration
     */
    public GeschlechtStDao() {
        super(GeschlechtSt.GESCHLECHT_ST, jooq.tables.pojos.GeschlechtSt.class);
    }

    /**
     * Create a new GeschlechtStDao with an attached configuration
     */
    public GeschlechtStDao(Configuration configuration) {
        super(GeschlechtSt.GESCHLECHT_ST, jooq.tables.pojos.GeschlechtSt.class, configuration);
    }

    @Override
    public String getId(jooq.tables.pojos.GeschlechtSt object) {
        return object.getGeschlecht();
    }

    /**
     * Fetch records that have <code>geschlecht BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.GeschlechtSt> fetchRangeOfGeschlecht(String lowerInclusive, String upperInclusive) {
        return fetchRange(GeschlechtSt.GESCHLECHT_ST.GESCHLECHT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>geschlecht IN (values)</code>
     */
    public List<jooq.tables.pojos.GeschlechtSt> fetchByGeschlecht(String... values) {
        return fetch(GeschlechtSt.GESCHLECHT_ST.GESCHLECHT, values);
    }

    /**
     * Fetch a unique record that has <code>geschlecht = value</code>
     */
    public jooq.tables.pojos.GeschlechtSt fetchOneByGeschlecht(String value) {
        return fetchOne(GeschlechtSt.GESCHLECHT_ST.GESCHLECHT, value);
    }
}
