/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.Icd10CodeSt;
import jooq.tables.records.Icd10CodeStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Icd10CodeStDao extends DAOImpl<Icd10CodeStRecord, jooq.tables.pojos.Icd10CodeSt, String> {

    /**
     * Create a new Icd10CodeStDao without any configuration
     */
    public Icd10CodeStDao() {
        super(Icd10CodeSt.ICD10_CODE_ST, jooq.tables.pojos.Icd10CodeSt.class);
    }

    /**
     * Create a new Icd10CodeStDao with an attached configuration
     */
    public Icd10CodeStDao(Configuration configuration) {
        super(Icd10CodeSt.ICD10_CODE_ST, jooq.tables.pojos.Icd10CodeSt.class, configuration);
    }

    @Override
    public String getId(jooq.tables.pojos.Icd10CodeSt object) {
        return object.getIcd10Code();
    }

    /**
     * Fetch records that have <code>icd10_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Icd10CodeSt> fetchRangeOfIcd10Code(String lowerInclusive, String upperInclusive) {
        return fetchRange(Icd10CodeSt.ICD10_CODE_ST.ICD10_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>icd10_code IN (values)</code>
     */
    public List<jooq.tables.pojos.Icd10CodeSt> fetchByIcd10Code(String... values) {
        return fetch(Icd10CodeSt.ICD10_CODE_ST.ICD10_CODE, values);
    }

    /**
     * Fetch a unique record that has <code>icd10_code = value</code>
     */
    public jooq.tables.pojos.Icd10CodeSt fetchOneByIcd10Code(String value) {
        return fetchOne(Icd10CodeSt.ICD10_CODE_ST.ICD10_CODE, value);
    }

    /**
     * Fetch records that have <code>beschreibung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Icd10CodeSt> fetchRangeOfBeschreibung(String lowerInclusive, String upperInclusive) {
        return fetchRange(Icd10CodeSt.ICD10_CODE_ST.BESCHREIBUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>beschreibung IN (values)</code>
     */
    public List<jooq.tables.pojos.Icd10CodeSt> fetchByBeschreibung(String... values) {
        return fetch(Icd10CodeSt.ICD10_CODE_ST.BESCHREIBUNG, values);
    }
}
