/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.NarkoseSt;
import jooq.tables.records.NarkoseStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NarkoseStDao extends DAOImpl<NarkoseStRecord, jooq.tables.pojos.NarkoseSt, Integer> {

    /**
     * Create a new NarkoseStDao without any configuration
     */
    public NarkoseStDao() {
        super(NarkoseSt.NARKOSE_ST, jooq.tables.pojos.NarkoseSt.class);
    }

    /**
     * Create a new NarkoseStDao with an attached configuration
     */
    public NarkoseStDao(Configuration configuration) {
        super(NarkoseSt.NARKOSE_ST, jooq.tables.pojos.NarkoseSt.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.NarkoseSt object) {
        return object.getNarkose();
    }

    /**
     * Fetch records that have <code>narkose BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.NarkoseSt> fetchRangeOfNarkose(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(NarkoseSt.NARKOSE_ST.NARKOSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>narkose IN (values)</code>
     */
    public List<jooq.tables.pojos.NarkoseSt> fetchByNarkose(Integer... values) {
        return fetch(NarkoseSt.NARKOSE_ST.NARKOSE, values);
    }

    /**
     * Fetch a unique record that has <code>narkose = value</code>
     */
    public jooq.tables.pojos.NarkoseSt fetchOneByNarkose(Integer value) {
        return fetchOne(NarkoseSt.NARKOSE_ST.NARKOSE, value);
    }

    /**
     * Fetch records that have <code>beschreibung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.NarkoseSt> fetchRangeOfBeschreibung(String lowerInclusive, String upperInclusive) {
        return fetchRange(NarkoseSt.NARKOSE_ST.BESCHREIBUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>beschreibung IN (values)</code>
     */
    public List<jooq.tables.pojos.NarkoseSt> fetchByBeschreibung(String... values) {
        return fetch(NarkoseSt.NARKOSE_ST.BESCHREIBUNG, values);
    }
}
