/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import jooq.tables.Operation;
import jooq.tables.records.OperationRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperationDao extends DAOImpl<OperationRecord, jooq.tables.pojos.Operation, Integer> {

    /**
     * Create a new OperationDao without any configuration
     */
    public OperationDao() {
        super(Operation.OPERATION, jooq.tables.pojos.Operation.class);
    }

    /**
     * Create a new OperationDao with an attached configuration
     */
    public OperationDao(Configuration configuration) {
        super(Operation.OPERATION, jooq.tables.pojos.Operation.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.Operation object) {
        return object.getOpId();
    }

    /**
     * Fetch records that have <code>op_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfOpId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.OP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>op_id IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByOpId(Integer... values) {
        return fetch(Operation.OPERATION.OP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>op_id = value</code>
     */
    public jooq.tables.pojos.Operation fetchOneByOpId(Integer value) {
        return fetchOne(Operation.OPERATION.OP_ID, value);
    }

    /**
     * Fetch records that have <code>beginn BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfBeginn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Operation.OPERATION.BEGINN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>beginn IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByBeginn(LocalDateTime... values) {
        return fetch(Operation.OPERATION.BEGINN, values);
    }

    /**
     * Fetch records that have <code>ende BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfEnde(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Operation.OPERATION.ENDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ende IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByEnde(LocalDateTime... values) {
        return fetch(Operation.OPERATION.ENDE, values);
    }

    /**
     * Fetch records that have <code>bauchtuecher_prae BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfBauchtuecherPrae(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.BAUCHTUECHER_PRAE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bauchtuecher_prae IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByBauchtuecherPrae(Integer... values) {
        return fetch(Operation.OPERATION.BAUCHTUECHER_PRAE, values);
    }

    /**
     * Fetch records that have <code>bauchtuecher_post BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfBauchtuecherPost(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.BAUCHTUECHER_POST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bauchtuecher_post IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByBauchtuecherPost(Integer... values) {
        return fetch(Operation.OPERATION.BAUCHTUECHER_POST, values);
    }

    /**
     * Fetch records that have <code>schnittzeit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfSchnittzeit(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Operation.OPERATION.SCHNITTZEIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>schnittzeit IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchBySchnittzeit(LocalDateTime... values) {
        return fetch(Operation.OPERATION.SCHNITTZEIT, values);
    }

    /**
     * Fetch records that have <code>nahtzeit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfNahtzeit(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Operation.OPERATION.NAHTZEIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nahtzeit IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByNahtzeit(LocalDateTime... values) {
        return fetch(Operation.OPERATION.NAHTZEIT, values);
    }

    /**
     * Fetch records that have <code>erstell_zeit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfErstellZeit(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Operation.OPERATION.ERSTELL_ZEIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>erstell_zeit IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByErstellZeit(LocalDateTime... values) {
        return fetch(Operation.OPERATION.ERSTELL_ZEIT, values);
    }

    /**
     * Fetch records that have <code>bearbeiter_zeit BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfBearbeiterZeit(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Operation.OPERATION.BEARBEITER_ZEIT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bearbeiter_zeit IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByBearbeiterZeit(LocalDateTime... values) {
        return fetch(Operation.OPERATION.BEARBEITER_ZEIT, values);
    }

    /**
     * Fetch records that have <code>storniert BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfStorniert(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Operation.OPERATION.STORNIERT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>storniert IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByStorniert(Boolean... values) {
        return fetch(Operation.OPERATION.STORNIERT, values);
    }

    /**
     * Fetch records that have <code>fall_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfFallId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.FALL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fall_id IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByFallId(Integer... values) {
        return fetch(Operation.OPERATION.FALL_ID, values);
    }

    /**
     * Fetch records that have <code>op_saal BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfOpSaal(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.OP_SAAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>op_saal IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByOpSaal(Integer... values) {
        return fetch(Operation.OPERATION.OP_SAAL, values);
    }

    /**
     * Fetch records that have <code>narkose_st BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfNarkoseSt(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.NARKOSE_ST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>narkose_st IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByNarkoseSt(Integer... values) {
        return fetch(Operation.OPERATION.NARKOSE_ST, values);
    }

    /**
     * Fetch records that have <code>op_typ_st BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfOpTypSt(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Operation.OPERATION.OP_TYP_ST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>op_typ_st IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByOpTypSt(Integer... values) {
        return fetch(Operation.OPERATION.OP_TYP_ST, values);
    }

    /**
     * Fetch records that have <code>ersteller BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfErsteller(String lowerInclusive, String upperInclusive) {
        return fetchRange(Operation.OPERATION.ERSTELLER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ersteller IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByErsteller(String... values) {
        return fetch(Operation.OPERATION.ERSTELLER, values);
    }

    /**
     * Fetch records that have <code>bearbeiter BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfBearbeiter(String lowerInclusive, String upperInclusive) {
        return fetchRange(Operation.OPERATION.BEARBEITER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bearbeiter IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByBearbeiter(String... values) {
        return fetch(Operation.OPERATION.BEARBEITER, values);
    }

    /**
     * Fetch records that have <code>geplant BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Operation> fetchRangeOfGeplant(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Operation.OPERATION.GEPLANT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>geplant IN (values)</code>
     */
    public List<jooq.tables.pojos.Operation> fetchByGeplant(Boolean... values) {
        return fetch(Operation.OPERATION.GEPLANT, values);
    }
}
