/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.OpsCodeSt;
import jooq.tables.records.OpsCodeStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpsCodeStDao extends DAOImpl<OpsCodeStRecord, jooq.tables.pojos.OpsCodeSt, String> {

    /**
     * Create a new OpsCodeStDao without any configuration
     */
    public OpsCodeStDao() {
        super(OpsCodeSt.OPS_CODE_ST, jooq.tables.pojos.OpsCodeSt.class);
    }

    /**
     * Create a new OpsCodeStDao with an attached configuration
     */
    public OpsCodeStDao(Configuration configuration) {
        super(OpsCodeSt.OPS_CODE_ST, jooq.tables.pojos.OpsCodeSt.class, configuration);
    }

    @Override
    public String getId(jooq.tables.pojos.OpsCodeSt object) {
        return object.getOpsCode();
    }

    /**
     * Fetch records that have <code>ops_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.OpsCodeSt> fetchRangeOfOpsCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(OpsCodeSt.OPS_CODE_ST.OPS_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ops_code IN (values)</code>
     */
    public List<jooq.tables.pojos.OpsCodeSt> fetchByOpsCode(String... values) {
        return fetch(OpsCodeSt.OPS_CODE_ST.OPS_CODE, values);
    }

    /**
     * Fetch a unique record that has <code>ops_code = value</code>
     */
    public jooq.tables.pojos.OpsCodeSt fetchOneByOpsCode(String value) {
        return fetchOne(OpsCodeSt.OPS_CODE_ST.OPS_CODE, value);
    }

    /**
     * Fetch records that have <code>beschreibung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.OpsCodeSt> fetchRangeOfBeschreibung(String lowerInclusive, String upperInclusive) {
        return fetchRange(OpsCodeSt.OPS_CODE_ST.BESCHREIBUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>beschreibung IN (values)</code>
     */
    public List<jooq.tables.pojos.OpsCodeSt> fetchByBeschreibung(String... values) {
        return fetch(OpsCodeSt.OPS_CODE_ST.BESCHREIBUNG, values);
    }
}
