/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.RolleSt;
import jooq.tables.records.RolleStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolleStDao extends DAOImpl<RolleStRecord, jooq.tables.pojos.RolleSt, Integer> {

    /**
     * Create a new RolleStDao without any configuration
     */
    public RolleStDao() {
        super(RolleSt.ROLLE_ST, jooq.tables.pojos.RolleSt.class);
    }

    /**
     * Create a new RolleStDao with an attached configuration
     */
    public RolleStDao(Configuration configuration) {
        super(RolleSt.ROLLE_ST, jooq.tables.pojos.RolleSt.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.RolleSt object) {
        return object.getRolle();
    }

    /**
     * Fetch records that have <code>rolle BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.RolleSt> fetchRangeOfRolle(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(RolleSt.ROLLE_ST.ROLLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rolle IN (values)</code>
     */
    public List<jooq.tables.pojos.RolleSt> fetchByRolle(Integer... values) {
        return fetch(RolleSt.ROLLE_ST.ROLLE, values);
    }

    /**
     * Fetch a unique record that has <code>rolle = value</code>
     */
    public jooq.tables.pojos.RolleSt fetchOneByRolle(Integer value) {
        return fetchOne(RolleSt.ROLLE_ST.ROLLE, value);
    }

    /**
     * Fetch records that have <code>bezeichnung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.RolleSt> fetchRangeOfBezeichnung(String lowerInclusive, String upperInclusive) {
        return fetchRange(RolleSt.ROLLE_ST.BEZEICHNUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bezeichnung IN (values)</code>
     */
    public List<jooq.tables.pojos.RolleSt> fetchByBezeichnung(String... values) {
        return fetch(RolleSt.ROLLE_ST.BEZEICHNUNG, values);
    }
}
