/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import jooq.tables.StationSt;
import jooq.tables.records.StationStRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StationStDao extends DAOImpl<StationStRecord, jooq.tables.pojos.StationSt, String> {

    /**
     * Create a new StationStDao without any configuration
     */
    public StationStDao() {
        super(StationSt.STATION_ST, jooq.tables.pojos.StationSt.class);
    }

    /**
     * Create a new StationStDao with an attached configuration
     */
    public StationStDao(Configuration configuration) {
        super(StationSt.STATION_ST, jooq.tables.pojos.StationSt.class, configuration);
    }

    @Override
    public String getId(jooq.tables.pojos.StationSt object) {
        return object.getStation();
    }

    /**
     * Fetch records that have <code>station BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchRangeOfStation(String lowerInclusive, String upperInclusive) {
        return fetchRange(StationSt.STATION_ST.STATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>station IN (values)</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchByStation(String... values) {
        return fetch(StationSt.STATION_ST.STATION, values);
    }

    /**
     * Fetch a unique record that has <code>station = value</code>
     */
    public jooq.tables.pojos.StationSt fetchOneByStation(String value) {
        return fetchOne(StationSt.STATION_ST.STATION, value);
    }

    /**
     * Fetch records that have <code>bezeichnung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchRangeOfBezeichnung(String lowerInclusive, String upperInclusive) {
        return fetchRange(StationSt.STATION_ST.BEZEICHNUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bezeichnung IN (values)</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchByBezeichnung(String... values) {
        return fetch(StationSt.STATION_ST.BEZEICHNUNG, values);
    }

    /**
     * Fetch records that have <code>bezeichnung_lang BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchRangeOfBezeichnungLang(String lowerInclusive, String upperInclusive) {
        return fetchRange(StationSt.STATION_ST.BEZEICHNUNG_LANG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bezeichnung_lang IN (values)</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchByBezeichnungLang(String... values) {
        return fetch(StationSt.STATION_ST.BEZEICHNUNG_LANG, values);
    }

    /**
     * Fetch records that have <code>stationstyp BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchRangeOfStationstyp(String lowerInclusive, String upperInclusive) {
        return fetchRange(StationSt.STATION_ST.STATIONSTYP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>stationstyp IN (values)</code>
     */
    public List<jooq.tables.pojos.StationSt> fetchByStationstyp(String... values) {
        return fetch(StationSt.STATION_ST.STATIONSTYP, values);
    }
}
